#!/bin/sh

# Test Environment, Logger subsystem.
# This script takes no arguments and returns full name of the
# valid temporary raw log file.
#
# Copyright (C) 2003 Test Environment authors (see file AUTHORS in the 
# root directory of the distribution).
#
# Test Environment is free software; you can redistribute it and/or 
# modify it under the terms of the GNU General Public License as 
# published by the Free Software Foundation; either version 2 of 
# the License, or (at your option) any later version.
# 
# Test Environment is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
# MA  02111-1307  USA
#
# Author: Igor B. Vasiliev <Igor.Vasiliev@oktetlabs.ru>

TE_LOG_PATH=${TE_LOG_DIR}
TE_TMP_LOG=${TE_LOG_PATH}/tmp_raw_log

if [ -z ${TE_LOG_DIR} ]; then
    echo "TE_LOG_DIR environment variable should be tuned"
    exit -1
fi

if [ ${#@} -ne 0 ]; then
    echo ""
    echo "Usage: te_log_init"
    echo ""
    exit -1
fi

echo -ne ${TE_TMP_LOG}
