#!/usr/bin/perl -w
#
# Test Environment: Logger subsystem
#
# Script takes no arguments, creates and initializes temporary raw log file.
# This script has to be called before Logging functionality will be used.
#
#
# Copyright (C) 2003-2006 Test Environment authors (see file AUTHORS in
# the root directory of the distribution).
#
# Test Environment is free software; you can redistribute it and/or 
# modify it under the terms of the GNU General Public License as 
# published by the Free Software Foundation; either version 2 of 
# the License, or (at your option) any later version.
# 
# Test Environment is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
# MA  02111-1307  USA
#
#
# Author: Igor B. Vasiliev <Igor.Vasiliev@oktetlabs.ru>
# Author: Andrew Rybchenko <Andrew.Rybchenko@oktetlabs.ru>
#
# $Id: $
#

use File::Path;

# Validate number of parameters
if (@ARGV != 0)
{
    print STDOUT "Usage: te_log_init\n";
    exit 1;
}

my $te_log_path = $ENV{TE_LOG_DIR};
if (length($te_log_path) == 0) 
{
    die("TE_LOG_DIR environment variable must be set\n");
}

eval { mkpath($te_log_path) };
if ($@)
{
    die("Couldn't create directory for logs: " . $te_log_path . ": " . $@);
}

my $te_log_raw  = $ENV{TE_LOG_RAW};

open(OUTFILE, ">" . $te_log_raw) or 
    die("Can't create raw log file: " . $te_log_raw . ": $!");

binmode OUTFILE;

# Write log file version 
print OUTFILE pack("C", 1);

close OUTFILE;

exit 0;
