#!/bin/sh
# SPDX-License-Identifier: Apache-2.0

# Test Environment, Logger subsystem.
# This script takes no arguments. It archives in the storage
# all files existing into temporary logger location.
#
# Copyright (C) 2004-2022 OKTET Labs Ltd. All rights reserved.
#

# ISSUES:
# 1. storage_config
# 2. storage_dir

# strg_local_to_storage(storage_config, local_dirname, st_obj_name, recursive,
#                      update)

