#!/bin/bash

# The script addes table of contents for HTML pages generated for all @groups.
# doxygen names these html files as group__<name>.html. It goes through the
# files and builds the table basing on <h{level}><a class="anchor">.... marks.
# The script honors different headings and supports multi-level contents

HTML_DIR=$TE_BASE/doc/generated/html

pushd $HTML_DIR > /dev/null

table_header='<div class="toc"><h3>Table of Contents</h3\><ul>'
table_footer='</ul></div>'

for group_file in group__*.html; do
    table_content=`cat $group_file | grep -A1 '<h[0-9]*><a class="anchor"' | \
        sed 's/^--$//' |
        sed 's/^.*<h\([0-9]*\)>.*id="\(\S*\)">.*/<li class="level\1"><a href="#\2">/' | \
        sed 's/^\(.*\)<\/h[0-9]*>$/\1<\/a><\/li>/'`
    table=`echo -n "${table_header} ${table_content} ${table_footer}" | tr '\n' ' '`

    sed -i "/<div class=\"contents\">/ i$table" $group_file
done

######################################################################
# now we need to add proper CSS to doxygen.css if it was missing there
######################################################################
# by default it's RO
chmod +rw $HTML_DIR/doxygen.css

toc_css=`cat<<EOF
div.toc {
        padding: 14px 25px;
        background-color: #F4F6FA;
        border: 1px solid #D8DFEE;
        border-radius: 7px 7px 7px 7px;
        float: right;
        height: auto;
        margin: 0 20px 10px 10px;
        width: 200px;
}
div.toc li {
        background: url("bdwn.png") no-repeat scroll 0 5px transparent;
        font: 10px/1.2 Verdana,DejaVu Sans,Geneva,sans-serif;
        margin-top: 5px;
        padding-left: 10px;
        padding-top: 2px;
}

div.toc h3 {
        font: bold 12px/1.2 Arial,FreeSans,sans-serif;
>-------color: #4665A2;
        border-bottom: 0 none;
        margin: 0;
}

div.toc ul {
        list-style: none outside none;
        border: medium none;
        padding: 0px;
}

div.toc li.level1 {
        margin-left: 0px;
}

div.toc li.level2 {
        margin-left: 15px;
}

div.toc li.level3 {
        margin-left: 30px;
}

div.toc li.level4 {
        margin-left: 45px;
}
EOF`

echo $toc_css >> $HTML_DIR/doxygen.css

