#!/usr/bin/perl

use strict;
use warnings;

use Fcntl qw/:flock/;

# Next comment is special, it will be changed to
# correct "use lib" when deploying.

#USE_LIB
use night_logs_cgi_aux::aux_funcs;

my $fh_lock = lock_caches();
my @caches = load_caches_list();
my $cli_path = get_cli_path();

umask 0027;

system("find \"$cli_path/\" -maxdepth 1 -regex \".*_update_[0-9]*[.]log\" ".
       "-ctime 3 -exec rm {} \\;");

foreach my $cache (@caches)
{
    my $rc;
    my $cur_day = int(time() / (24 * 60 * 60));
    my $cmd_str = "$cli_path/te_get_nlogs_results --update-cache=".
                  $cache->{"cache_path"}." --include-compromised ".
                  " --log-path=".$cache->{"logs_source"}." 2>&1 ".
                  " >>$cli_path/".$cache->{"id"}."_update_${cur_day}.log";

    print "$cmd_str\n";
    $rc = system("cd /tmp/; $cmd_str");
    if ($rc != 0)
    {
        print "Updating cache failed\n";
    }
}

unlock_caches($fh_lock);
