#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 OKTET Ltd.
"""Generate the Sphinx navigation from the Doxygen group hierarchy.

The API hierarchy is already expressed in the sources: every module carries
``@defgroup <name> <title>`` and ``@ingroup <parent>``.  Doxygen honours that
only when the parent is itself ``@defgroup``-ed somewhere.  A number of TE's
container groups are not - they exist only as hand-written pages under
``doc/sphinx/pages/`` which fake the Doxygen anchor with an explicit
``.. _doxid-group__<name>:`` label.  For those, Doxygen silently drops the
parent link, doxyrest emits no child toctree, and the modules disappear from
the sidebar unless a human remembers to list them by hand.  They did not: this
script was written because 116 of 258 documented modules had no sidebar entry.

So the child lists are generated here instead, from the same ``@ingroup`` tags
the sources already maintain.  For every hand-written container page this
writes ``doc/sphinx/pages/_toctree/<name>.inc`` holding a hidden toctree of
that group's children, which the page includes.  Adding a module with a correct
``@ingroup`` is now all it takes to have it appear in the navigation.

Run after doxyrest, so that generated pages can be resolved; with --check the
generated files are compared against what is on disk instead of rewritten.
"""
from __future__ import annotations

import argparse
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

# Kept in step with the INPUT tag of the top-level Doxyfile.
DOXYGEN_INPUT = ("lib/tools", "engine", "include", "lib", "agents",
                 "tools/rgt", "tools/trc", "doc/dox_resources")
SOURCE_SUFFIXES = (".h", ".c", ".dox")

COMMENT_BLOCK = re.compile(r"/\*\*(.*?)\*/", re.S)
DEFGROUP = re.compile(r"[@\\]defgroup\s+(\S+)[ \t]*(.*)")
INGROUP = re.compile(r"[@\\]ingroup\s+(\S+)")

# Hand-written pages stand in for container groups Doxygen does not define, so
# they declare their own place in the tree in a leading RST comment:
#   ..
#     te-parent: te_engine
TE_PARENT = re.compile(r"^\s+te-parent:\s*(\S+)\s*$", re.M)
# Children are ordered by title, which is right for an API listing but not for
# the narrative sections; a page may state where it belongs in the reading
# order instead:
#   ..
#     te-order: 20
TE_ORDER = re.compile(r"^\s+te-order:\s*(\d+)\s*$", re.M)
INCLUDE = re.compile(r"^\.\. include:: (?:pages/)?_toctree/(\S+)\.inc\s*$", re.M)
# Hand-written children are addressed from the Sphinx source root, which also
# tells them apart from the entries doxyrest wrote.
INJECTED_PREFIX = "\t/pages/"
UNORDERED = 10 ** 6
# The page holding the root of the tree; it owns the top-level toctree.
ROOT = "te"

HEADER = """..
  SPDX-License-Identifier: Apache-2.0
  Generated by scripts/docs/gen_toctrees.py from the @defgroup/@ingroup tags
  in the sources - do not edit.

.. toctree::
\t:hidden:

"""


class Group:
    def __init__(self, name: str, title: str, origin: Path):
        self.name = name
        self.title = title
        self.origin = origin
        self.parent: str | None = None
        self.page: Path | None = None
        self.order = UNORDERED


def scan_sources(te_base: Path) -> dict[str, Group]:
    """Collect every @defgroup in the tree Doxygen is pointed at."""
    groups: dict[str, Group] = {}
    for root in DOXYGEN_INPUT:
        for path in sorted((te_base / root).rglob("*")):
            if path.suffix not in SOURCE_SUFFIXES or not path.is_file():
                continue
            text = path.read_text(errors="replace")
            if "defgroup" not in text:
                continue
            for block in COMMENT_BLOCK.findall(text):
                found = DEFGROUP.search(block)
                if not found:
                    continue
                name, title = found.group(1), found.group(2).strip()
                group = Group(name, title, path.relative_to(te_base))
                parent = INGROUP.search(block)
                if parent:
                    group.parent = parent.group(1)
                previous = groups.get(name)
                if previous is None:
                    groups[name] = group
                    continue
                # Re-opening a group elsewhere is normal - the parent is
                # usually stated once - so only two different parents are a
                # real contradiction about where the group belongs.
                if group.parent is None:
                    continue
                if previous.parent is None:
                    previous.parent = group.parent
                elif previous.parent != group.parent:
                    raise SystemExit(
                        f"{path}: @defgroup {name} is @ingroup {group.parent} "
                        f"but @ingroup {previous.parent} in {previous.origin}")
    return groups


def scan_pages(pages: Path) -> dict[str, Group]:
    """Collect the hand-written pages and the parent each one declares."""
    nodes: dict[str, Group] = {}
    root = Group(ROOT, "", pages.parent / "index.rst")
    root.page = root.origin
    nodes[ROOT] = root
    for path in sorted(pages.glob("*.rst")):
        text = path.read_text()
        declared = TE_PARENT.search(text)
        if not declared:
            raise SystemExit(
                f"{path}: no 'te-parent:' marker, so the page cannot be "
                f"placed in the navigation")
        title = re.search(r"^(\S.*)\n[=~-]{3,}\s*$", text, re.M)
        node = Group(page_name(path), title.group(1).strip() if title
                     else path.stem, path)
        node.parent = declared.group(1)
        node.page = path
        order = TE_ORDER.search(text)
        if order:
            node.order = int(order.group(1))
        nodes[node.name] = node
    return nodes


def page_name(path: Path) -> str:
    """The group a page stands in for: group_te_engine.rst -> te_engine."""
    stem = path.stem
    return stem[len("group_"):] if stem.startswith("group_") else stem


def page_of(pages: Path, name: str) -> Path | None:
    """The hand-written page standing in for a group, if there is one."""
    for stem in (f"group_{name}", name):
        candidate = pages / f"{stem}.rst"
        if candidate.is_file():
            return candidate
    return None


def render(parent: Group, children: list[Group], pages: Path) -> str:
    """A hidden toctree listing children, hand-written pages preferred.

    Toctree entries are resolved against the including document, so paths are
    relative to the parent page; generated pages are addressed absolutely.
    """
    home = parent.page.parent
    lines = []
    for child in children:
        page = child.page or page_of(pages, child.name)
        if page:
            lines.append("\t" + str(page.relative_to(home)))
        else:
            lines.append(f"\t/generated/group_{child.name}.rst")
    return HEADER + "\n".join(lines) + "\n"


def inject(generated: Path, parent: Group, kids: list[Group]) -> bool:
    """Add hand-written children to a generated container's toctree.

    Doxygen owns the containers, so doxyrest writes their pages and nests the
    modules underneath.  It cannot know about a page that is prose rather than
    a documented group, so those are added here, addressed from the Sphinx
    source root.
    """
    target = generated / f"group_{parent.name}.rst"
    if not target.is_file():
        print(f"{target}: doxyrest generated no page for {parent.name}, so "
              f"its hand-written children have nowhere to attach",
              file=sys.stderr)
        return False
    text = target.read_text()
    entries = "".join(f"{INJECTED_PREFIX}{k.page.stem}.rst\n" for k in kids)
    if entries in text:
        return True
    toctree = re.search(r"^\.\. toctree::\n(?:[ \t]+\S.*\n|[ \t]*\n)*", text,
                        re.M)
    if toctree:
        end = toctree.end()
        while end > 0 and text[end - 1] == "\n" and text[end - 2:end] == "\n\n":
            end -= 1
        text = text[:end] + entries + text[end:]
    else:
        title = re.search(r"^\S.*\n[=]{3,}[ \t]*\n", text, re.M)
        at = title.end() if title else len(text)
        text = (text[:at] + "\n.. toctree::\n\t:hidden:\n\n" + entries
                + text[at:])
    target.write_text(text)
    return True


def build_tree(groups: dict[str, Group], nodes: dict[str, Group]) -> \
        dict[str, list[Group]]:
    """Children of every container, from @ingroup tags and page markers.

    A hand-written page shadows the group of the same name: the page carries
    the narrative and the generated child list, so the group's own generated
    page is not linked.  Everything else keeps the Doxygen hierarchy, which
    doxyrest already turns into a toctree wherever the parent is a real group.
    """
    known = dict(groups)
    known.update(nodes)
    children: dict[str, list[Group]] = {}
    for node in known.values():
        if node.name == ROOT or node.parent is None:
            continue
        if node.parent not in known:
            raise SystemExit(
                f"{node.origin}: {node.name} belongs to {node.parent}, which "
                f"is neither a @defgroup nor a page in doc/sphinx/pages/")
        children.setdefault(node.parent, []).append(node)
    return children


def check_reachable(xml_dir: Path, seeds: set[str]) -> list[str]:
    """Groups Doxygen knows about that no navigation path can reach.

    The source scan cannot see groups nested lexically inside another group's
    @{ @} block - Doxygen infers that parent and doxyrest emits a toctree for
    it - so the authoritative hierarchy is the one in the Doxygen XML.  The
    seeds are the groups the hand-written pages hand off to; walking the XML
    from there is what proves the sidebar reaches everything.
    """
    # <innergroup> carries the child's title as text and its identity in
    # refid, so the compound ids have to be collected before they can be
    # turned back into group names.
    by_id: dict[str, str] = {}
    refs: dict[str, list[str]] = {}
    for path in sorted(xml_dir.glob("group__*.xml")):
        compound = ET.parse(path).getroot().find("compounddef")
        # @page compounds land in group__*.xml too; they hang off a group's
        # own page rather than the navigation, so they are not checked here.
        if compound.get("kind") != "group":
            continue
        name = compound.findtext("compoundname")
        by_id[compound.get("id")] = name
        refs[name] = [inner.get("refid") for inner in
                      compound.iterfind("innergroup") if inner.get("refid")]
    children = {name: [by_id[r] for r in ids if r in by_id]
                for name, ids in refs.items()}
    seen: set[str] = set()
    queue = [name for name in seeds if name in children]
    while queue:
        name = queue.pop()
        if name in seen:
            continue
        seen.add(name)
        queue += children.get(name, [])
    return sorted(name for name in children if name not in seen)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--te-base", default=None,
                        help="TE source root (default: derived from $TE_BASE)")
    parser.add_argument("--check", action="store_true",
                        help="fail if the files on disk are not up to date")
    parser.add_argument("--generated", default=None,
                        help="doxyrest output directory; when given, "
                             "hand-written children of a generated container "
                             "are added to its toctree")
    parser.add_argument("--xml", default=None,
                        help="Doxygen XML directory; when given, also verify "
                             "that every group Doxygen found is reachable")
    args = parser.parse_args()

    te_base = Path(args.te_base) if args.te_base \
        else Path(__file__).resolve().parents[2]
    pages = te_base / "doc" / "sphinx" / "pages"
    out_dir = pages / "_toctree"

    groups = scan_sources(te_base)
    nodes = scan_pages(pages)
    children = build_tree(groups, nodes)

    # Only containers with a hand-written page need a generated child list.
    # Where the parent is a real Doxygen group, doxyrest emits its own.
    wanted = {name: kids for name, kids in children.items() if name in nodes}

    out_dir.mkdir(parents=True, exist_ok=True)
    stale = set(out_dir.glob("*.inc"))
    failed = False
    for parent, kids in sorted(wanted.items()):
        kids.sort(key=lambda g: (g.order, g.title.lower()))
        target = out_dir / f"{parent}.inc"
        stale.discard(target)
        content = render(nodes[parent], kids, pages)
        if args.check:
            current = target.read_text() if target.is_file() else ""
            if current != content:
                print(f"{target}: out of date, re-run "
                      f"scripts/docs/gen_toctrees.py", file=sys.stderr)
                failed = True
        else:
            target.write_text(content)

    for leftover in sorted(stale):
        if args.check:
            print(f"{leftover}: no longer generated, re-run "
                  f"scripts/docs/gen_toctrees.py", file=sys.stderr)
            failed = True
        else:
            leftover.unlink()

    # Containers Doxygen owns get their hand-written children added to the
    # page doxyrest produced for them.
    if args.generated:
        for name, kids in sorted(children.items()):
            if name in nodes or name not in groups:
                continue
            manual = [k for k in kids if k.page]
            if manual:
                manual.sort(key=lambda g: (g.order, g.title.lower()))
                if not inject(Path(args.generated), groups[name], manual):
                    failed = True

    # A page and its generated child list have to agree: an include with no
    # generated file breaks the build, and a generated file nobody includes is
    # a subtree that silently never reaches the sidebar.
    included = {}
    for path in sorted(pages.glob("*.rst")) + [pages.parent / "index.rst"]:
        for name in INCLUDE.findall(path.read_text()):
            included.setdefault(name, path)
    for name, path in sorted(included.items()):
        if name not in wanted:
            print(f"{path}: includes _toctree/{name}.inc, which is not "
                  f"generated - the page has no children", file=sys.stderr)
            failed = True
    for name in sorted(wanted):
        if name not in included:
            print(f"{nodes[name].page}: has children but does not include "
                  f"_toctree/{name}.inc", file=sys.stderr)
            failed = True

    if args.xml:
        seeds = {child.name for kids in wanted.values() for child in kids}
        for name in check_reachable(Path(args.xml), seeds):
            print(f"@defgroup {name} is not reachable from any page: give it "
                  f"an @ingroup that leads to doc/sphinx/pages/",
                  file=sys.stderr)
            failed = True

    if failed:
        return 1
    if not args.check:
        print(f"{Path(sys.argv[0]).name}: wrote {len(wanted)} child lists "
              f"covering {sum(len(k) for k in wanted.values())} entries",
              file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
