#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 OKTET Ltd.
#
# Render "dispatcher.sh --help" into a reStructuredText fragment included by
# the Dispatcher documentation page, so the option list cannot go stale.
#
# Usage: gen_dispatcher_options.sh [output-file]
# Default output: ${TE_BASE}/doc/sphinx/pages/dispatcher_options.inc

set -e

[[ -z "${TE_BASE}" ]] && export TE_BASE="$(cd "$(dirname "$0")/../.." && pwd -P)"

OUTPUT="${1:-${TE_BASE}/doc/sphinx/pages/dispatcher_options.inc}"

if [[ ! -x "${TE_BASE}/dispatcher.sh" ]]; then
    echo "$0: cannot find ${TE_BASE}/dispatcher.sh" >&2
    exit 1
fi

# dispatcher.sh writes meta_data.json into the current directory even for
# --help, so run it in a scratch directory. Defaults derived from that
# directory are substituted back to their variable names below.
scratch="$(mktemp -d)"
trap 'rm -rf "${scratch}"' EXIT

help_text="$(cd "${scratch}" && "${TE_BASE}/dispatcher.sh" --help)"

if [[ -z "${help_text}" ]]; then
    echo "$0: dispatcher.sh --help produced no output" >&2
    exit 1
fi

{
    echo ".."
    echo "  SPDX-License-Identifier: Apache-2.0"
    echo "  Generated by scripts/docs/gen_dispatcher_options.sh - do not edit."
    echo
    echo ".. code-block:: none"
    echo
    printf '%s\n' "${help_text}" \
        | sed -e "s|${scratch}|\${TE_RUN_DIR}|g" \
              -e "s|${TE_BASE}|\${TE_BASE}|g" \
              -e "s|${HOME}|\${HOME}|g" \
        | sed -e 's/^/\t/' -e 's/[[:space:]]*$//'
    echo
} > "${OUTPUT}"
