#! /bin/sh
#
# Test Coverage Estimation
#
#
# Copyright (C) 2005 Test Environment authors (see file AUTHORS in
# the root directory of the distribution).
#
# Test Environment is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# Test Environment is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA  02111-1307  USA
#
#
# Author: Artem V. Andreev <Artem.Andreev@oktetlabs.ru>
#
# $Id$
#

outfile=$1
nopattern="$2"
yespattern="$3"

awk " BEGIN { yescount = nocount = 0 }
/$nopattern/ { nocount++ } 
/$yespattern/ { yescount++ }
END { sum = yescount + nocount
      if (sum == 0)
          print \"0.00 0\"
      else
          printf \"%.2f %d\\n\", (yescount * 100) / sum, sum; 
}
" $outfile

