#! /bin/sh
#
# Test Coverage Estimation
#
# A wrapper around tce_gcc to simulate g++
#
#
# Copyright (C) 2003-2018 OKTET Labs.
#
# Author Artem V. Andreev <Artem.Andreev@oktetlabs.ru>
#
#

export TCE_CC=${TCE_CXX}
exec tce_gcc "$@"
