#! /bin/sh
#
# Test Coverage Estimation
#
#
# Copyright (C) 2005 Test Environment authors (see file AUTHORS in
# the root directory of the distribution).
#
# Test Environment is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# Test Environment is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA  02111-1307  USA
#
#
# Author Artem V. Andreev <Artem.Andreev@oktetlabs.ru>
#
# $Id$
#

cd `dirname $1`
case "$1" in
    *.gcda) version=`od -tc $1 | awk '{ print $9 "." $7; exit 0}'`
    gcov=`eval echo \$\{TE_GCOV_${version/./_}\}`
    test -z "$gcov" && gcov=gcov-$version
    ;;
    *.da)     gcov=${TE_GCOV_OLD:-gcov-3.3} ;;
    *) echo "Strange data file $1" >&2; exit 1 ;;
esac
if ! which $gcov >/dev/null; then
    gcov=gcov
fi
exec $gcov -l -c -b `basename $1` >/dev/null
