/* cwmp_decls.h
   Generated by wsdl2h 1.2.9l from cwmp.xsd and cwmp_typemap.dat
   2010-02-10 19:06:41 GMT
   Copyright (C) 2001-2007 Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/* NOTE:

 - Compile this file with soapcpp2 to complete the code generation process.
 - Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control schema namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) to browse this file.
 - Use wsdl2h option -l to view the software license terms.

   DO NOT include this file directly into your project.
   Include only the soapcpp2-generated headers and source code files.
*/

//gsoapopt cw

/******************************************************************************\
 *                                                                            *
 * urn:dslforum-org:cwmp-1-1                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

cwmp = "urn:dslforum-org:cwmp-1-1"

*/

//gsoap cwmp  schema namespace:	urn:dslforum-org:cwmp-1-1
//gsoap cwmp  schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Schema Types                                                               *
 *                                                                            *
\******************************************************************************/


/// Built-in type "SOAP-ENC:base64".
struct SOAP_ENC__base64 { unsigned char *__ptr; int __size; };

/// Primitive built-in type "xs:anySimpleType"
typedef char* xsd__anySimpleType;

/// Built-in type "xs:boolean".
enum xsd__boolean { xsd__boolean__false_, xsd__boolean__true_ };

/// Built-in attribute "SOAP-ENV:mustUnderstand".
typedef char* _SOAP_ENV__mustUnderstand;


/// Typedef synonym for struct MethodList.
typedef struct MethodList MethodList;

/// Typedef synonym for struct cwmp__FaultStruct.
typedef struct cwmp__FaultStruct cwmp__FaultStruct;

/// Typedef synonym for struct cwmp__DeviceIdStruct.
typedef struct cwmp__DeviceIdStruct cwmp__DeviceIdStruct;

/// Typedef synonym for struct cwmp__EventStruct.
typedef struct cwmp__EventStruct cwmp__EventStruct;

/// Typedef synonym for struct EventList.
typedef struct EventList EventList;

/// Typedef synonym for struct cwmp__ParameterValueStruct.
typedef struct cwmp__ParameterValueStruct cwmp__ParameterValueStruct;

/// Typedef synonym for struct ParameterValueList.
typedef struct ParameterValueList ParameterValueList;

/// Typedef synonym for struct cwmp__ParameterInfoStruct.
typedef struct cwmp__ParameterInfoStruct cwmp__ParameterInfoStruct;

/// Typedef synonym for struct ParameterInfoList.
typedef struct ParameterInfoList ParameterInfoList;

/// Typedef synonym for struct ParameterNames.
typedef struct ParameterNames ParameterNames;

/// Typedef synonym for struct AccessList.
typedef struct AccessList AccessList;

/// Typedef synonym for struct cwmp__SetParameterAttributesStruct.
typedef struct cwmp__SetParameterAttributesStruct cwmp__SetParameterAttributesStruct;

/// Typedef synonym for struct SetParameterAttributesList.
typedef struct SetParameterAttributesList SetParameterAttributesList;

/// Typedef synonym for struct cwmp__ParameterAttributeStruct.
typedef struct cwmp__ParameterAttributeStruct cwmp__ParameterAttributeStruct;

/// Typedef synonym for struct ParameterAttributeList.
typedef struct ParameterAttributeList ParameterAttributeList;

/// Typedef synonym for struct cwmp__QueuedTransferStruct.
typedef struct cwmp__QueuedTransferStruct cwmp__QueuedTransferStruct;

/// Typedef synonym for struct TransferList.
typedef struct TransferList TransferList;

/// Typedef synonym for struct cwmp__AllQueuedTransferStruct.
typedef struct cwmp__AllQueuedTransferStruct cwmp__AllQueuedTransferStruct;

/// Typedef synonym for struct AllTransferList.
typedef struct AllTransferList AllTransferList;

/// Typedef synonym for struct VoucherList.
typedef struct VoucherList VoucherList;

/// Typedef synonym for struct cwmp__OptionStruct.
typedef struct cwmp__OptionStruct cwmp__OptionStruct;

/// Typedef synonym for struct OptionList.
typedef struct OptionList OptionList;

/// Typedef synonym for struct cwmp__ArgStruct.
typedef struct cwmp__ArgStruct cwmp__ArgStruct;

/// Typedef synonym for struct FileTypeArg.
typedef struct FileTypeArg FileTypeArg;

/// Typedef synonym for struct _cwmp__ID.
typedef struct _cwmp__ID _cwmp__ID;

/// Typedef synonym for struct _cwmp__HoldRequests.
typedef struct _cwmp__HoldRequests _cwmp__HoldRequests;

/// Typedef synonym for struct _cwmp__Fault.
typedef struct _cwmp__Fault _cwmp__Fault;

/// Typedef synonym for struct _cwmp__GetRPCMethods.
typedef struct _cwmp__GetRPCMethods _cwmp__GetRPCMethods;

/// Typedef synonym for struct _cwmp__GetRPCMethodsResponse.
typedef struct _cwmp__GetRPCMethodsResponse _cwmp__GetRPCMethodsResponse;

/// Typedef synonym for struct _cwmp__SetParameterValues.
typedef struct _cwmp__SetParameterValues _cwmp__SetParameterValues;

/// Typedef synonym for struct _cwmp__SetParameterValuesResponse.
typedef struct _cwmp__SetParameterValuesResponse _cwmp__SetParameterValuesResponse;

/// Typedef synonym for struct _cwmp__GetParameterValues.
typedef struct _cwmp__GetParameterValues _cwmp__GetParameterValues;

/// Typedef synonym for struct _cwmp__GetParameterValuesResponse.
typedef struct _cwmp__GetParameterValuesResponse _cwmp__GetParameterValuesResponse;

/// Typedef synonym for struct _cwmp__GetParameterNames.
typedef struct _cwmp__GetParameterNames _cwmp__GetParameterNames;

/// Typedef synonym for struct _cwmp__GetParameterNamesResponse.
typedef struct _cwmp__GetParameterNamesResponse _cwmp__GetParameterNamesResponse;

/// Typedef synonym for struct _cwmp__SetParameterAttributes.
typedef struct _cwmp__SetParameterAttributes _cwmp__SetParameterAttributes;

/// Typedef synonym for struct _cwmp__SetParameterAttributesResponse.
typedef struct _cwmp__SetParameterAttributesResponse _cwmp__SetParameterAttributesResponse;

/// Typedef synonym for struct _cwmp__GetParameterAttributes.
typedef struct _cwmp__GetParameterAttributes _cwmp__GetParameterAttributes;

/// Typedef synonym for struct _cwmp__GetParameterAttributesResponse.
typedef struct _cwmp__GetParameterAttributesResponse _cwmp__GetParameterAttributesResponse;

/// Typedef synonym for struct _cwmp__AddObject.
typedef struct _cwmp__AddObject _cwmp__AddObject;

/// Typedef synonym for struct _cwmp__AddObjectResponse.
typedef struct _cwmp__AddObjectResponse _cwmp__AddObjectResponse;

/// Typedef synonym for struct _cwmp__DeleteObject.
typedef struct _cwmp__DeleteObject _cwmp__DeleteObject;

/// Typedef synonym for struct _cwmp__DeleteObjectResponse.
typedef struct _cwmp__DeleteObjectResponse _cwmp__DeleteObjectResponse;

/// Typedef synonym for struct _cwmp__Download.
typedef struct _cwmp__Download _cwmp__Download;

/// Typedef synonym for struct _cwmp__DownloadResponse.
typedef struct _cwmp__DownloadResponse _cwmp__DownloadResponse;

/// Typedef synonym for struct _cwmp__Reboot.
typedef struct _cwmp__Reboot _cwmp__Reboot;

/// Typedef synonym for struct _cwmp__RebootResponse.
typedef struct _cwmp__RebootResponse _cwmp__RebootResponse;

/// Typedef synonym for struct _cwmp__GetQueuedTransfers.
typedef struct _cwmp__GetQueuedTransfers _cwmp__GetQueuedTransfers;

/// Typedef synonym for struct _cwmp__GetQueuedTransfersResponse.
typedef struct _cwmp__GetQueuedTransfersResponse _cwmp__GetQueuedTransfersResponse;

/// Typedef synonym for struct _cwmp__ScheduleInform.
typedef struct _cwmp__ScheduleInform _cwmp__ScheduleInform;

/// Typedef synonym for struct _cwmp__ScheduleInformResponse.
typedef struct _cwmp__ScheduleInformResponse _cwmp__ScheduleInformResponse;

/// Typedef synonym for struct _cwmp__SetVouchers.
typedef struct _cwmp__SetVouchers _cwmp__SetVouchers;

/// Typedef synonym for struct _cwmp__SetVouchersResponse.
typedef struct _cwmp__SetVouchersResponse _cwmp__SetVouchersResponse;

/// Typedef synonym for struct _cwmp__GetOptions.
typedef struct _cwmp__GetOptions _cwmp__GetOptions;

/// Typedef synonym for struct _cwmp__GetOptionsResponse.
typedef struct _cwmp__GetOptionsResponse _cwmp__GetOptionsResponse;

/// Typedef synonym for struct _cwmp__Upload.
typedef struct _cwmp__Upload _cwmp__Upload;

/// Typedef synonym for struct _cwmp__UploadResponse.
typedef struct _cwmp__UploadResponse _cwmp__UploadResponse;

/// Typedef synonym for struct _cwmp__FactoryReset.
typedef struct _cwmp__FactoryReset _cwmp__FactoryReset;

/// Typedef synonym for struct _cwmp__FactoryResetResponse.
typedef struct _cwmp__FactoryResetResponse _cwmp__FactoryResetResponse;

/// Typedef synonym for struct _cwmp__GetAllQueuedTransfers.
typedef struct _cwmp__GetAllQueuedTransfers _cwmp__GetAllQueuedTransfers;

/// Typedef synonym for struct _cwmp__GetAllQueuedTransfersResponse.
typedef struct _cwmp__GetAllQueuedTransfersResponse _cwmp__GetAllQueuedTransfersResponse;

/// Typedef synonym for struct _cwmp__Inform.
typedef struct _cwmp__Inform _cwmp__Inform;

/// Typedef synonym for struct _cwmp__InformResponse.
typedef struct _cwmp__InformResponse _cwmp__InformResponse;

/// Typedef synonym for struct _cwmp__TransferComplete.
typedef struct _cwmp__TransferComplete _cwmp__TransferComplete;

/// Typedef synonym for struct _cwmp__TransferCompleteResponse.
typedef struct _cwmp__TransferCompleteResponse _cwmp__TransferCompleteResponse;

/// Typedef synonym for struct _cwmp__AutonomousTransferComplete.
typedef struct _cwmp__AutonomousTransferComplete _cwmp__AutonomousTransferComplete;

/// Typedef synonym for struct _cwmp__AutonomousTransferCompleteResponse.
typedef struct _cwmp__AutonomousTransferCompleteResponse _cwmp__AutonomousTransferCompleteResponse;

/// Typedef synonym for struct _cwmp__Kicked.
typedef struct _cwmp__Kicked _cwmp__Kicked;

/// Typedef synonym for struct _cwmp__KickedResponse.
typedef struct _cwmp__KickedResponse _cwmp__KickedResponse;

/// Typedef synonym for struct _cwmp__RequestDownload.
typedef struct _cwmp__RequestDownload _cwmp__RequestDownload;

/// Typedef synonym for struct _cwmp__RequestDownloadResponse.
typedef struct _cwmp__RequestDownloadResponse _cwmp__RequestDownloadResponse;

/// union of values from "xs:unsignedInt"
/// union of values from "xs:unsignedInt"
/// union of values from "xs:unsignedInt"
/// union of values from "xs:unsignedInt"
/// union of values from "xs:unsignedInt"
/// union of values from "xs:unsignedInt"
typedef char* cwmp__FaultCodeType;

/// "urn:dslforum-org:cwmp-1-1":ParameterKeyType is a simpleType restriction of xs:string.
/// Length of this string is within 0..32 characters
typedef char* cwmp__ParameterKeyType:32;

/// "urn:dslforum-org:cwmp-1-1":CommandKeyType is a simpleType restriction of xs:string.
/// Length of this string is within 0..32 characters
typedef char* cwmp__CommandKeyType:32;

/// "urn:dslforum-org:cwmp-1-1":ObjectNameType is a simpleType restriction of xs:string.
/// Length of this string is within 0..256 characters
/// Content pattern is ".*\\."
typedef char* cwmp__ObjectNameType ".*\\.":256;

/// "urn:dslforum-org:cwmp-1-1":FaultStruct is a complexType.
/// @brief Fault information for TransferComplete and AutonomousTransferComplete
struct cwmp__FaultStruct
{
/// @brief Transfer fault codes

/// union of values from "xs:unsignedInt"
/// union of values from "xs:unsignedInt"
/// union of values from "xs:unsignedInt"
    char*                                                              
                                         FaultCode                      1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         FaultString                    1;	///< Required element.
};

/// "urn:dslforum-org:cwmp-1-1":DeviceIdStruct is a complexType.
struct cwmp__DeviceIdStruct
{
/// Length of this string is within 0..64 characters
    char*                                                              
                                         Manufacturer                   1;	///< Required element.
/// Length of this string is exactly 6 characters
/// Content pattern is "[0-9A-F]{6}"
    char*                                                              
                                         OUI                            1;	///< Required element.
/// Length of this string is within 0..64 characters
    char*                                                              
                                         ProductClass                   1;	///< Required element.
/// Length of this string is within 0..64 characters
    char*                                                              
                                         SerialNumber                   1;	///< Required element.
};

/// "urn:dslforum-org:cwmp-1-1":EventStruct is a complexType.
struct cwmp__EventStruct
{
/// Length of this string is within 0..64 characters
/// Content pattern is "0 BOOTSTRAP"
/// Content pattern is "1 BOOT"
/// Content pattern is "2 PERIODIC"
/// Content pattern is "3 SCHEDULED"
/// Content pattern is "4 VALUE CHANGE"
/// Content pattern is "5 KICKED"
/// Content pattern is "6 CONNECTION REQUEST"
/// Content pattern is "7 TRANSFER COMPLETE"
/// Content pattern is "8 DIAGNOSTICS COMPLETE"
/// Content pattern is "9 REQUEST DOWNLOAD"
/// Content pattern is "10 AUTONOMOUS TRANSFER COMPLETE"
/// Content pattern is "\\d+( \\S+)+"
/// Content pattern is "M Reboot"
/// Content pattern is "M ScheduleInform"
/// Content pattern is "M Download"
/// Content pattern is "M Upload"
/// Content pattern is "M \\S+"
/// Content pattern is "M X_\\S+"
/// Content pattern is "X [0-9A-F]{6} .*"
    char*                                                              
                                         EventCode                      1;	///< Required element.
/// Element CommandKey of type "urn:dslforum-org:cwmp-1-1":CommandKeyType.
    cwmp__CommandKeyType                 CommandKey                     1;	///< Required element.
};

/// "urn:dslforum-org:cwmp-1-1":ParameterValueStruct is a complexType.
struct cwmp__ParameterValueStruct
{
/// Length of this string is within 0..256 characters
    char*                                                              
                                         Name                           1;	///< Required element.
/// Element Value of type xs:anySimpleType.
    xsd__anySimpleType                   Value                          1;	///< Required element.
};

/// "urn:dslforum-org:cwmp-1-1":ParameterInfoStruct is a complexType.
struct cwmp__ParameterInfoStruct
{
/// Length of this string is within 0..256 characters
    char*                                                              
                                         Name                           1;	///< Required element.
/// Element Writable of type xs:boolean.
    enum xsd__boolean                    Writable                       1;	///< Required element.
};

/// "urn:dslforum-org:cwmp-1-1":SetParameterAttributesStruct is a complexType.
struct cwmp__SetParameterAttributesStruct
{
/// Length of this string is within 0..256 characters
    char*                                                              
                                        *Name                          ;	///< Nullable pointer.
/// Element NotificationChange of type xs:boolean.
    enum xsd__boolean                    NotificationChange             1;	///< Required element.
    enum _cwmp__SetParameterAttributesStruct_Notification
    {
/// @brief Notification off. The CPE need not inform the ACS of a change to the specified parameter(s)
	_cwmp__SetParameterAttributesStruct_Notification__0 = 0,	///< xs:int value="0"
/// @brief Passive notification. Whenever the specified parameter value changes, the CPE MUST include the new value in the ParameterList in the Inform message that is sent the next time a session is established to the ACS
	_cwmp__SetParameterAttributesStruct_Notification__1 = 1,	///< xs:int value="1"
/// @brief Active notification. Whenever the specified parameter value changes, the CPE MUST initiate a session to the ACS, and include the new value in the ParameterList in the associated Inform message
	_cwmp__SetParameterAttributesStruct_Notification__2 = 2,	///< xs:int value="2"
    }
                                         Notification                   1;	///< Required element.
/// Element AccessListChange of type xs:boolean.
    enum xsd__boolean                    AccessListChange               1;	///< Required element.
/// Element AccessList of type "urn:dslforum-org:cwmp-1-1":AccessList.
    struct AccessList*                   AccessList_                    1;	///< Required element.
};

/// "urn:dslforum-org:cwmp-1-1":ParameterAttributeStruct is a complexType.
struct cwmp__ParameterAttributeStruct
{
/// Length of this string is within 0..256 characters
    char*                                                              
                                         Name                           1;	///< Required element.
    enum _cwmp__ParameterAttributeStruct_Notification
    {
	_cwmp__ParameterAttributeStruct_Notification__0 = 0,	///< xs:int value="0"
	_cwmp__ParameterAttributeStruct_Notification__1 = 1,	///< xs:int value="1"
	_cwmp__ParameterAttributeStruct_Notification__2 = 2,	///< xs:int value="2"
    }
                                         Notification                   1;	///< Required element.
/// Element AccessList of type "urn:dslforum-org:cwmp-1-1":AccessList.
    struct AccessList*                   AccessList_                    1;	///< Required element.
};

/// "urn:dslforum-org:cwmp-1-1":QueuedTransferStruct is a complexType.
struct cwmp__QueuedTransferStruct
{
/// Element CommandKey of type "urn:dslforum-org:cwmp-1-1":CommandKeyType.
    cwmp__CommandKeyType                 CommandKey                     1;	///< Required element.
    enum _cwmp__QueuedTransferStruct_State
    {
/// @brief 1 - Not yet started
	_cwmp__QueuedTransferStruct_State__1 = 1,	///< xs:int value="1"
/// @brief 2 - In progress
	_cwmp__QueuedTransferStruct_State__2 = 2,	///< xs:int value="2"
/// @brief 3 - Completed
	_cwmp__QueuedTransferStruct_State__3 = 3,	///< xs:int value="3"
    }
                                         State                          1;	///< Required element.
};

/// "urn:dslforum-org:cwmp-1-1":AllQueuedTransferStruct is a complexType.
struct cwmp__AllQueuedTransferStruct
{
/// Element CommandKey of type "urn:dslforum-org:cwmp-1-1":CommandKeyType.
    cwmp__CommandKeyType                 CommandKey                     1;	///< Required element.
    enum _cwmp__AllQueuedTransferStruct_State
    {
/// @brief 1 - Not yet started
	_cwmp__AllQueuedTransferStruct_State__1 = 1,	///< xs:int value="1"
/// @brief 2 - In progress
	_cwmp__AllQueuedTransferStruct_State__2 = 2,	///< xs:int value="2"
/// @brief 3 - Completed
	_cwmp__AllQueuedTransferStruct_State__3 = 3,	///< xs:int value="3"
    }
                                         State                          1;	///< Required element.
/// Element IsDownload of type xs:boolean.
    enum xsd__boolean                    IsDownload                     1;	///< Required element.
/// Length of this string is within 0..64 characters
/// Content pattern is "1 Firmware Upgrade Image"
/// Content pattern is "2 Web Content"
/// Content pattern is "3 Vendor Configuration File"
/// Content pattern is "4 Vendor Log File"
/// Content pattern is "X [0-9A-F]{6} .*"
    char*                                                              
                                         FileType                       1;	///< Required element.
/// Element FileSize of type xs:unsignedInt.
    unsigned int                         FileSize                       1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         TargetFileName                 1;	///< Required element.
};

/// "urn:dslforum-org:cwmp-1-1":OptionStruct is a complexType.
struct cwmp__OptionStruct
{
/// Length of this string is within 0..64 characters
    char*                                                              
                                         OptionName                     1;	///< Required element.
/// Element VoucherSN of type xs:unsignedInt.
    unsigned int                         VoucherSN                      1;	///< Required element.
    enum _cwmp__OptionStruct_State
    {
/// @brief Option is disabled and not setup
	_cwmp__OptionStruct_State__0 = 0,	///< xs:unsignedInt value="0"
/// @brief Option is enabled and not setup
	_cwmp__OptionStruct_State__1 = 1,	///< xs:unsignedInt value="1"
/// @brief Option is disabled and setup
	_cwmp__OptionStruct_State__2 = 2,	///< xs:unsignedInt value="2"
/// @brief Option is enabled and setup
	_cwmp__OptionStruct_State__3 = 3,	///< xs:unsignedInt value="3"
    }
                                         State                          1;	///< Required element.
    enum _cwmp__OptionStruct_Mode
    {
/// @brief 0 - Disabled
	_cwmp__OptionStruct_Mode__0 = 0,	///< xs:int value="0"
/// @brief 1 - Enabled with expiration
	_cwmp__OptionStruct_Mode__1 = 1,	///< xs:int value="1"
/// @brief 2 - Enabled without expiration
	_cwmp__OptionStruct_Mode__2 = 2,	///< xs:int value="2"
    }
                                         Mode                           1;	///< Required element.
/// Element StartDate of type xs:dateTime.
    time_t                               StartDate                      1;	///< Required element.
/// Element ExpirationDate of type xs:dateTime.
    time_t*                              ExpirationDate                 0;	///< Optional element.
    enum _cwmp__OptionStruct_IsTransferable
    {
/// @brief Non-transferable
	_cwmp__OptionStruct_IsTransferable__0 = 0,	///< xs:int value="0"
/// @brief Transferable
	_cwmp__OptionStruct_IsTransferable__1 = 1,	///< xs:int value="1"
    }
                                         IsTransferable                 1;	///< Required element.
};

/// "urn:dslforum-org:cwmp-1-1":ArgStruct is a complexType.
struct cwmp__ArgStruct
{
/// Length of this string is within 0..64 characters
    char*                                                              
                                         Name                           1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         Value                          1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":Fault of complexType.

/// "urn:dslforum-org:cwmp-1-1":Fault is a complexType.
struct _cwmp__Fault
{
/// Element FaultCode of type "urn:dslforum-org:cwmp-1-1":FaultCodeType.
    cwmp__FaultCodeType                  FaultCode                      1;	///< Required element.
/// Element FaultString of type xs:string.
    char*                                FaultString                    0;	///< Optional element.
/// Size of SetParameterValuesFault array is 0..unbounded
    int                                  __sizeSetParameterValuesFault ;
    struct _cwmp__Fault_SetParameterValuesFault
    {
/// Element ParameterName of type xs:string.
    char*                                ParameterName                  1;	///< Required element.
/// Element FaultCode of type "urn:dslforum-org:cwmp-1-1":FaultCodeType.
    cwmp__FaultCodeType                  FaultCode                      1;	///< Required element.
/// Element FaultString of type xs:string.
    char*                                FaultString                    0;	///< Optional element.
    }                                   *SetParameterValuesFault        0;
};


/// Element "urn:dslforum-org:cwmp-1-1":GetRPCMethods of complexType.
/// @brief GeRPCMethods message - Annex A.3.1.1

/// "urn:dslforum-org:cwmp-1-1":GetRPCMethods is a complexType.
struct _cwmp__GetRPCMethods
{
};


/// Element "urn:dslforum-org:cwmp-1-1":GetRPCMethodsResponse of complexType.
/// @brief GeRPCMethodsResponse message - Annex A.3.1.1

/// "urn:dslforum-org:cwmp-1-1":GetRPCMethodsResponse is a complexType.
struct _cwmp__GetRPCMethodsResponse
{
/// Element MethodList of type "urn:dslforum-org:cwmp-1-1":MethodList.
    struct MethodList*                   MethodList_                    1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":SetParameterValues of complexType.
/// @brief SetParameterValues message - Annex A.3.2.1

/// "urn:dslforum-org:cwmp-1-1":SetParameterValues is a complexType.
struct _cwmp__SetParameterValues
{
/// Element ParameterList of type "urn:dslforum-org:cwmp-1-1":ParameterValueList.
    struct ParameterValueList*           ParameterList                  1;	///< Required element.
/// Element ParameterKey of type "urn:dslforum-org:cwmp-1-1":ParameterKeyType.
    cwmp__ParameterKeyType               ParameterKey                   1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":SetParameterValuesResponse of complexType.
/// @brief SetParameterValuesResponse message - Annex A.3.2.1

/// "urn:dslforum-org:cwmp-1-1":SetParameterValuesResponse is a complexType.
struct _cwmp__SetParameterValuesResponse
{
    enum _cwmp__SetParameterValuesResponse_Status
    {
/// @brief All Parameter changes have been validated and applied
	_cwmp__SetParameterValuesResponse_Status__0 = 0,	///< xs:int value="0"
/// @brief All Parameter changes have been validated and committed, but some or all are not yet applied (for example, if a reboot is required before the new values are applied)
	_cwmp__SetParameterValuesResponse_Status__1 = 1,	///< xs:int value="1"
    }
                                         Status                         1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":GetParameterValues of complexType.
/// @brief GetParameterValues message - Annex A.3.2.2

/// "urn:dslforum-org:cwmp-1-1":GetParameterValues is a complexType.
struct _cwmp__GetParameterValues
{
/// Element ParameterNames of type "urn:dslforum-org:cwmp-1-1":ParameterNames.
    struct ParameterNames*               ParameterNames_                1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":GetParameterValuesResponse of complexType.
/// @brief GetParameterValuesResponse message - Annex A.3.2.2

/// "urn:dslforum-org:cwmp-1-1":GetParameterValuesResponse is a complexType.
struct _cwmp__GetParameterValuesResponse
{
/// Element ParameterList of type "urn:dslforum-org:cwmp-1-1":ParameterValueList.
    struct ParameterValueList*           ParameterList                  1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":GetParameterNames of complexType.
/// @brief GetParameterNames message - Annex A.3.2.3

/// "urn:dslforum-org:cwmp-1-1":GetParameterNames is a complexType.
struct _cwmp__GetParameterNames
{
/// Length of this string is within 0..256 characters
    char*                                                              
                                        *ParameterPath                 ;	///< Nullable pointer.
/// Element NextLevel of type xs:boolean.
    enum xsd__boolean                    NextLevel                      1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":GetParameterNamesResponse of complexType.
/// @brief GetParameterNamesResponse message - Annex A.3.2.3

/// "urn:dslforum-org:cwmp-1-1":GetParameterNamesResponse is a complexType.
struct _cwmp__GetParameterNamesResponse
{
/// Element ParameterList of type "urn:dslforum-org:cwmp-1-1":ParameterInfoList.
    struct ParameterInfoList*            ParameterList                  1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":SetParameterAttributes of complexType.
/// @brief SetParameterAttributes message - Annex A.3.2.4

/// "urn:dslforum-org:cwmp-1-1":SetParameterAttributes is a complexType.
struct _cwmp__SetParameterAttributes
{
/// Element ParameterList of type "urn:dslforum-org:cwmp-1-1":SetParameterAttributesList.
    struct SetParameterAttributesList*   ParameterList                  1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":SetParameterAttributesResponse of complexType.
/// @brief SetParameterAttributesResponse message - Annex A.3.2.4

/// "urn:dslforum-org:cwmp-1-1":SetParameterAttributesResponse is a complexType.
struct _cwmp__SetParameterAttributesResponse
{
};


/// Element "urn:dslforum-org:cwmp-1-1":GetParameterAttributes of complexType.
/// @brief GetParameterAttributes message - Annex A.3.2.5

/// "urn:dslforum-org:cwmp-1-1":GetParameterAttributes is a complexType.
struct _cwmp__GetParameterAttributes
{
/// Element ParameterNames of type "urn:dslforum-org:cwmp-1-1":ParameterNames.
    struct ParameterNames*               ParameterNames_                1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":GetParameterAttributesResponse of complexType.
/// @brief GetParameterAttributesResponse message - Annex A.3.2.5

/// "urn:dslforum-org:cwmp-1-1":GetParameterAttributesResponse is a complexType.
struct _cwmp__GetParameterAttributesResponse
{
/// Element ParameterList of type "urn:dslforum-org:cwmp-1-1":ParameterAttributeList.
    struct ParameterAttributeList*       ParameterList                  1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":AddObject of complexType.
/// @brief AddObject message - Annex A.3.2.6

/// "urn:dslforum-org:cwmp-1-1":AddObject is a complexType.
struct _cwmp__AddObject
{
/// Element ObjectName of type "urn:dslforum-org:cwmp-1-1":ObjectNameType.
    cwmp__ObjectNameType                 ObjectName                     1;	///< Required element.
/// Element ParameterKey of type "urn:dslforum-org:cwmp-1-1":ParameterKeyType.
    cwmp__ParameterKeyType               ParameterKey                   1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":AddObjectResponse of complexType.
/// @brief AddObjectResponse message - Annex A.3.2.6

/// "urn:dslforum-org:cwmp-1-1":AddObjectResponse is a complexType.
struct _cwmp__AddObjectResponse
{
/// Value range is [1..]
    unsigned int                                                       
                                         InstanceNumber                 1;	///< Required element.
    enum _cwmp__AddObjectResponse_Status
    {
/// @brief The object has been created
	_cwmp__AddObjectResponse_Status__0 = 0,	///< xs:int value="0"
/// @brief The object creation has been validated and committed, but not yet applied
	_cwmp__AddObjectResponse_Status__1 = 1,	///< xs:int value="1"
    }
                                         Status                         1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":DeleteObject of complexType.
/// @brief DeleteObject message - Annex A.3.2.7

/// "urn:dslforum-org:cwmp-1-1":DeleteObject is a complexType.
struct _cwmp__DeleteObject
{
/// Element ObjectName of type "urn:dslforum-org:cwmp-1-1":ObjectNameType.
    cwmp__ObjectNameType                 ObjectName                     1;	///< Required element.
/// Element ParameterKey of type "urn:dslforum-org:cwmp-1-1":ParameterKeyType.
    cwmp__ParameterKeyType               ParameterKey                   1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":DeleteObjectResponse of complexType.
/// @brief DeleteObjectResponse message - Annex A.3.2.7

/// "urn:dslforum-org:cwmp-1-1":DeleteObjectResponse is a complexType.
struct _cwmp__DeleteObjectResponse
{
    enum _cwmp__DeleteObjectResponse_Status
    {
/// @brief The object has been deleted
	_cwmp__DeleteObjectResponse_Status__0 = 0,	///< xs:int value="0"
/// @brief The object deletion has been validated and committed, but not yet applied
	_cwmp__DeleteObjectResponse_Status__1 = 1,	///< xs:int value="1"
    }
                                         Status                         1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":Download of complexType.
/// @brief Download message - Annex A.3.2.8

/// "urn:dslforum-org:cwmp-1-1":Download is a complexType.
struct _cwmp__Download
{
/// Element CommandKey of type "urn:dslforum-org:cwmp-1-1":CommandKeyType.
    cwmp__CommandKeyType                 CommandKey                     1;	///< Required element.
/// Length of this string is within 0..64 characters
/// Content pattern is "1 Firmware Upgrade Image"
/// Content pattern is "2 Web Content"
/// Content pattern is "3 Vendor Configuration File"
/// Content pattern is "X [0-9A-F]{6} .*"
    char*                                                              
                                         FileType                       1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         URL                            1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         Username                       1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         Password                       1;	///< Required element.
/// Element FileSize of type xs:unsignedInt.
    unsigned int                         FileSize                       1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         TargetFileName                 1;	///< Required element.
/// Element DelaySeconds of type xs:unsignedInt.
    unsigned int                         DelaySeconds                   1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         SuccessURL                     1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         FailureURL                     1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":DownloadResponse of complexType.
/// @brief DownloadResponse message - Annex A.3.2.8

/// "urn:dslforum-org:cwmp-1-1":DownloadResponse is a complexType.
struct _cwmp__DownloadResponse
{
    enum _cwmp__DownloadResponse_Status
    {
/// @brief Download has completed and been applied
	_cwmp__DownloadResponse_Status__0 = 0,	///< xs:int value="0"
/// @brief Download has not yet been completed and applied
	_cwmp__DownloadResponse_Status__1 = 1,	///< xs:int value="1"
    }
                                         Status                         1;	///< Required element.
/// Element StartTime of type xs:dateTime.
    time_t                               StartTime                      1;	///< Required element.
/// Element CompleteTime of type xs:dateTime.
    time_t                               CompleteTime                   1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":Reboot of complexType.
/// @brief Reboot message - Annex A.3.2.9

/// "urn:dslforum-org:cwmp-1-1":Reboot is a complexType.
struct _cwmp__Reboot
{
/// Element CommandKey of type "urn:dslforum-org:cwmp-1-1":CommandKeyType.
    cwmp__CommandKeyType                 CommandKey                     1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":RebootResponse of complexType.
/// @brief RebootResponse message - Annex A.3.2.9

/// "urn:dslforum-org:cwmp-1-1":RebootResponse is a complexType.
struct _cwmp__RebootResponse
{
};


/// Element "urn:dslforum-org:cwmp-1-1":GetQueuedTransfers of complexType.
/// @brief GetQueuedTransfers message - Annex A.4.1.1

/// "urn:dslforum-org:cwmp-1-1":GetQueuedTransfers is a complexType.
struct _cwmp__GetQueuedTransfers
{
};


/// Element "urn:dslforum-org:cwmp-1-1":GetQueuedTransfersResponse of complexType.
/// @brief GetQueuedTransfersResponse message - Annex A.4.1.1

/// "urn:dslforum-org:cwmp-1-1":GetQueuedTransfersResponse is a complexType.
struct _cwmp__GetQueuedTransfersResponse
{
/// Element TransferList of type "urn:dslforum-org:cwmp-1-1":TransferList.
    struct TransferList*                 TransferList_                  1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":ScheduleInform of complexType.
/// @brief ScheduleInform message - Annex A.4.1.2

/// "urn:dslforum-org:cwmp-1-1":ScheduleInform is a complexType.
struct _cwmp__ScheduleInform
{
/// Element DelaySeconds of type xs:unsignedInt.
    unsigned int                         DelaySeconds                   1;	///< Required element.
/// Element CommandKey of type "urn:dslforum-org:cwmp-1-1":CommandKeyType.
    cwmp__CommandKeyType                 CommandKey                     1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":ScheduleInformResponse of complexType.
/// @brief ScheduleInformResponse message - Annex A.4.1.2

/// "urn:dslforum-org:cwmp-1-1":ScheduleInformResponse is a complexType.
struct _cwmp__ScheduleInformResponse
{
};


/// Element "urn:dslforum-org:cwmp-1-1":SetVouchers of complexType.
/// @brief SetVouchers message - Annex A.4.1.3

/// "urn:dslforum-org:cwmp-1-1":SetVouchers is a complexType.
struct _cwmp__SetVouchers
{
/// Element VoucherList of type "urn:dslforum-org:cwmp-1-1":VoucherList.
    struct VoucherList*                  VoucherList_                   1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":SetVouchersResponse of complexType.
/// @brief SetVouchersResponse message - Annex A.4.1.3

/// "urn:dslforum-org:cwmp-1-1":SetVouchersResponse is a complexType.
struct _cwmp__SetVouchersResponse
{
};


/// Element "urn:dslforum-org:cwmp-1-1":GetOptions of complexType.
/// @brief GetOptions message - Annex A.4.1.4

/// "urn:dslforum-org:cwmp-1-1":GetOptions is a complexType.
struct _cwmp__GetOptions
{
/// Length of this string is within 0..64 characters
    char*                                                              
                                         OptionName                     1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":GetOptionsResponse of complexType.
/// @brief GetOptionsResponse message - Annex A.4.1.4

/// "urn:dslforum-org:cwmp-1-1":GetOptionsResponse is a complexType.
struct _cwmp__GetOptionsResponse
{
/// Element OptionList of type "urn:dslforum-org:cwmp-1-1":OptionList.
    struct OptionList*                   OptionList_                    1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":Upload of complexType.
/// @brief Upload message - Annex A.4.1.5

/// "urn:dslforum-org:cwmp-1-1":Upload is a complexType.
struct _cwmp__Upload
{
/// Element CommandKey of type "urn:dslforum-org:cwmp-1-1":CommandKeyType.
    cwmp__CommandKeyType                 CommandKey                     1;	///< Required element.
/// Length of this string is within 0..64 characters
/// Content pattern is "1 Vendor Configuration File"
/// Content pattern is "2 Vendor Log File"
/// Content pattern is "X [0-9A-F]{6} .*"
    char*                                                              
                                         FileType                       1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         URL                            1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         Username                       1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         Password                       1;	///< Required element.
/// Element DelaySeconds of type xs:unsignedInt.
    unsigned int                         DelaySeconds                   1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":UploadResponse of complexType.
/// @brief UploadResponse message - Annex A.4.1.5

/// "urn:dslforum-org:cwmp-1-1":UploadResponse is a complexType.
struct _cwmp__UploadResponse
{
    enum _cwmp__UploadResponse_Status
    {
/// @brief Upload has been completed
	_cwmp__UploadResponse_Status__0 = 0,	///< xs:int value="0"
/// @brief Upload has not yet completed
	_cwmp__UploadResponse_Status__1 = 1,	///< xs:int value="1"
    }
                                         Status                         1;	///< Required element.
/// Element StartTime of type xs:dateTime.
    time_t                               StartTime                      1;	///< Required element.
/// Element CompleteTime of type xs:dateTime.
    time_t                               CompleteTime                   1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":FactoryReset of complexType.
/// @brief FactoryReset message - Annex A.4.1.6

/// "urn:dslforum-org:cwmp-1-1":FactoryReset is a complexType.
struct _cwmp__FactoryReset
{
};


/// Element "urn:dslforum-org:cwmp-1-1":FactoryResetResponse of complexType.
/// @brief FactoryResetResponse message - Annex A.4.1.6

/// "urn:dslforum-org:cwmp-1-1":FactoryResetResponse is a complexType.
struct _cwmp__FactoryResetResponse
{
};


/// Element "urn:dslforum-org:cwmp-1-1":GetAllQueuedTransfers of complexType.
/// @brief GetAllQueuedTransfers message - Annex A.4.1.7

/// "urn:dslforum-org:cwmp-1-1":GetAllQueuedTransfers is a complexType.
struct _cwmp__GetAllQueuedTransfers
{
};


/// Element "urn:dslforum-org:cwmp-1-1":GetAllQueuedTransfersResponse of complexType.
/// @brief GetAllQueuedTransfersResponse message - Annex A.4.1.7

/// "urn:dslforum-org:cwmp-1-1":GetAllQueuedTransfersResponse is a complexType.
struct _cwmp__GetAllQueuedTransfersResponse
{
/// Element TransferList of type "urn:dslforum-org:cwmp-1-1":AllTransferList.
    struct AllTransferList*              TransferList_                  1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":Inform of complexType.
/// @brief Inform message - Annex A.3.3.1

/// "urn:dslforum-org:cwmp-1-1":Inform is a complexType.
struct _cwmp__Inform
{
/// Element DeviceId of type "urn:dslforum-org:cwmp-1-1":DeviceIdStruct.
    struct cwmp__DeviceIdStruct*         DeviceId                       1;	///< Required element.
/// Element Event of type "urn:dslforum-org:cwmp-1-1":EventList.
    struct EventList*                    Event                          1;	///< Required element.
/// Element MaxEnvelopes of type xs:unsignedInt.
    unsigned int                         MaxEnvelopes                   1;	///< Required element.
/// Element CurrentTime of type xs:dateTime.
    time_t                               CurrentTime                    1;	///< Required element.
/// Element RetryCount of type xs:unsignedInt.
    unsigned int                         RetryCount                     1;	///< Required element.
/// Element ParameterList of type "urn:dslforum-org:cwmp-1-1":ParameterValueList.
    struct ParameterValueList*           ParameterList                  1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":InformResponse of complexType.
/// @brief InformResponse message - Annex A.3.3.1

/// "urn:dslforum-org:cwmp-1-1":InformResponse is a complexType.
struct _cwmp__InformResponse
{
/// Element MaxEnvelopes of type xs:unsignedInt.
    unsigned int                         MaxEnvelopes                   1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":TransferComplete of complexType.
/// @brief TransferComplete message - Annex A.3.3.2

/// "urn:dslforum-org:cwmp-1-1":TransferComplete is a complexType.
struct _cwmp__TransferComplete
{
/// Element CommandKey of type "urn:dslforum-org:cwmp-1-1":CommandKeyType.
    cwmp__CommandKeyType                 CommandKey                     1;	///< Required element.
/// Element FaultStruct of type "urn:dslforum-org:cwmp-1-1":FaultStruct.
    struct cwmp__FaultStruct*            FaultStruct                    1;	///< Required element.
/// Element StartTime of type xs:dateTime.
    time_t                               StartTime                      1;	///< Required element.
/// Element CompleteTime of type xs:dateTime.
    time_t                               CompleteTime                   1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":TransferCompleteResponse of complexType.
/// @brief TransferCompleteResponse message - Annex A.3.3.2

/// "urn:dslforum-org:cwmp-1-1":TransferCompleteResponse is a complexType.
struct _cwmp__TransferCompleteResponse
{
};


/// Element "urn:dslforum-org:cwmp-1-1":AutonomousTransferComplete of complexType.
/// @brief AutonomousTransferComplete message - Annex A.3.3.3

/// "urn:dslforum-org:cwmp-1-1":AutonomousTransferComplete is a complexType.
struct _cwmp__AutonomousTransferComplete
{
/// Length of this string is within 0..1024 characters
    char*                                                              
                                         AnnounceURL                    1;	///< Required element.
/// Length of this string is within 0..1024 characters
    char*                                                              
                                         TransferURL                    1;	///< Required element.
/// Element IsDownload of type xs:boolean.
    enum xsd__boolean                    IsDownload                     1;	///< Required element.
/// Length of this string is within 0..64 characters
/// Content pattern is "1 Firmware Upgrade Image"
/// Content pattern is "2 Web Content"
/// Content pattern is "3 Vendor Configuration File"
/// Content pattern is "4 Vendor Log File"
/// Content pattern is "X [0-9A-F]{6} .*"
    char*                                                              
                                         FileType                       1;	///< Required element.
/// Element FileSize of type xs:unsignedInt.
    unsigned int                         FileSize                       1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         TargetFileName                 1;	///< Required element.
/// Element FaultStruct of type "urn:dslforum-org:cwmp-1-1":FaultStruct.
    struct cwmp__FaultStruct*            FaultStruct                    1;	///< Required element.
/// Element StartTime of type xs:dateTime.
    time_t                               StartTime                      1;	///< Required element.
/// Element CompleteTime of type xs:dateTime.
    time_t                               CompleteTime                   1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":AutonomousTransferCompleteResponse of complexType.
/// @brief AutonomousTransferCompleteResponse message - Annex A.3.3.3

/// "urn:dslforum-org:cwmp-1-1":AutonomousTransferCompleteResponse is a complexType.
struct _cwmp__AutonomousTransferCompleteResponse
{
};


/// Element "urn:dslforum-org:cwmp-1-1":Kicked of complexType.
/// @brief Kicked message - Annex A.4.2.1

/// "urn:dslforum-org:cwmp-1-1":Kicked is a complexType.
struct _cwmp__Kicked
{
/// Length of this string is within 0..32 characters
    char*                                                              
                                         Command                        1;	///< Required element.
/// Length of this string is within 0..64 characters
    char*                                                              
                                         Referer                        1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         Arg                            1;	///< Required element.
/// Length of this string is within 0..1024 characters
    char*                                                              
                                         Next                           1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":KickedResponse of complexType.
/// @brief KickedResponse message - Annex A.4.2.1

/// "urn:dslforum-org:cwmp-1-1":KickedResponse is a complexType.
struct _cwmp__KickedResponse
{
/// Length of this string is within 0..1024 characters
    char*                                                              
                                         NextURL                        1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":RequestDownload of complexType.
/// @brief RequestDownload message - Annex A.4.2.2

/// "urn:dslforum-org:cwmp-1-1":RequestDownload is a complexType.
struct _cwmp__RequestDownload
{
/// Length of this string is within 0..64 characters
/// Content pattern is "1 Firmware Upgrade Image"
/// Content pattern is "2 Web Content"
/// Content pattern is "3 Vendor Configuration File"
/// Content pattern is "X [0-9A-F]{6} .*"
    char*                                                              
                                         FileType                       1;	///< Required element.
/// Element FileTypeArg of type "urn:dslforum-org:cwmp-1-1":FileTypeArg.
    struct FileTypeArg*                  FileTypeArg_                   1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":RequestDownloadResponse of complexType.
/// @brief RequestDownloadResponse message - Annex A.4.2.2

/// "urn:dslforum-org:cwmp-1-1":RequestDownloadResponse is a complexType.
struct _cwmp__RequestDownloadResponse
{
};

/// "urn:dslforum-org:cwmp-1-1":MethodList is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of xs:string
struct MethodList
{
/// Pointer to array of char*.
    char*                               *__ptrstring                   ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":EventList is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "urn:dslforum-org:cwmp-1-1":EventStruct
struct EventList
{
/// Pointer to array of struct cwmp__EventStruct*.
    struct cwmp__EventStruct*           *__ptrEventStruct              ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":ParameterValueList is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "urn:dslforum-org:cwmp-1-1":ParameterValueStruct
struct ParameterValueList
{
/// Pointer to array of struct cwmp__ParameterValueStruct*.
    struct cwmp__ParameterValueStruct*  *__ptrParameterValueStruct     ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":ParameterInfoList is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "urn:dslforum-org:cwmp-1-1":ParameterInfoStruct
struct ParameterInfoList
{
/// Pointer to array of struct cwmp__ParameterInfoStruct*.
    struct cwmp__ParameterInfoStruct*   *__ptrParameterInfoStruct      ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":ParameterNames is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of xs:string
struct ParameterNames
{
/// Pointer to array of char*.
    char*                               *__ptrstring                   ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":AccessList is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of xs:string
struct AccessList
{
/// Pointer to array of char*.
    char*                               *__ptrstring                   ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":SetParameterAttributesList is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "urn:dslforum-org:cwmp-1-1":SetParameterAttributesStruct
struct SetParameterAttributesList
{
/// Pointer to array of struct cwmp__SetParameterAttributesStruct*.
    struct cwmp__SetParameterAttributesStruct* *__ptrSetParameterAttributesStruct;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":ParameterAttributeList is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "urn:dslforum-org:cwmp-1-1":ParameterAttributeStruct
struct ParameterAttributeList
{
/// Pointer to array of struct cwmp__ParameterAttributeStruct*.
    struct cwmp__ParameterAttributeStruct* *__ptrParameterAttributeStruct ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":TransferList is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "urn:dslforum-org:cwmp-1-1":QueuedTransferStruct
struct TransferList
{
/// Pointer to array of struct cwmp__QueuedTransferStruct*.
    struct cwmp__QueuedTransferStruct*  *__ptrQueuedTransferStruct     ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":AllTransferList is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "urn:dslforum-org:cwmp-1-1":AllQueuedTransferStruct
struct AllTransferList
{
/// Pointer to array of struct cwmp__AllQueuedTransferStruct*.
    struct cwmp__AllQueuedTransferStruct* *__ptrAllQueuedTransferStruct  ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":VoucherList is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of SOAP-ENC:base64
struct VoucherList
{
/// Pointer to array of struct SOAP_ENC__base64*.
    struct SOAP_ENC__base64*            *__ptrbase64                   ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":OptionList is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "urn:dslforum-org:cwmp-1-1":OptionStruct
struct OptionList
{
/// Pointer to array of struct cwmp__OptionStruct*.
    struct cwmp__OptionStruct*          *__ptrOptionStruct             ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":FileTypeArg is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "urn:dslforum-org:cwmp-1-1":ArgStruct
struct FileTypeArg
{
/// Pointer to array of struct cwmp__ArgStruct*.
    struct cwmp__ArgStruct*             *__ptrArgStruct                ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};


/// Element "urn:dslforum-org:cwmp-1-1":ID of complexType.

/// "urn:dslforum-org:cwmp-1-1":ID is a complexType with simpleContent.
struct _cwmp__ID
{
/// __item wraps 'xs:string' simpleContent.
    char*                                __item                        ;
/// Imported attribute reference SOAP-ENV:mustUnderstand.
   @_SOAP_ENV__mustUnderstand            SOAP_ENV__mustUnderstand       1;	///< Required attribute.
};


/// Element "urn:dslforum-org:cwmp-1-1":HoldRequests of complexType.

/// "urn:dslforum-org:cwmp-1-1":HoldRequests is a complexType with simpleContent.
struct _cwmp__HoldRequests
{
/// __item wraps 'xs:unsignedInt' simpleContent.
    unsigned int                         __item                        ;
/// Imported attribute reference SOAP-ENV:mustUnderstand.
   @_SOAP_ENV__mustUnderstand            SOAP_ENV__mustUnderstand       1;	///< Required attribute.
};

/* End of cwmp_decls.h */


int __cwmp__GetRPCMethods(_cwmp__GetRPCMethods *cwmp__GetRPCMethods, _cwmp__GetRPCMethodsResponse *cwmp__GetRPCMethodsResponse);
int __cwmp__Inform(_cwmp__Inform *cwmp__Inform, _cwmp__InformResponse *cwmp__InformResponse);
int __cwmp__TransferComplete(_cwmp__TransferComplete *cwmp__TransferComplete, _cwmp__TransferCompleteResponse *cwmp__TransferCompleteResponse);
int __cwmp__AutonomousTransferComplete(_cwmp__AutonomousTransferComplete *cwmp__AutonomousTransferComplete, _cwmp__AutonomousTransferCompleteResponse *cwmp__AutonomousTransferCompleteResponse);
int __cwmp__RequestDownload(_cwmp__RequestDownload *cwmp__RequestDownload, _cwmp__RequestDownloadResponse *cwmp__RequestDownloadResponse);
int __cwmp__Kicked(_cwmp__Kicked *cwmp__Kicked, _cwmp__KickedResponse *cwmp__KickedResponse);


struct SOAP_ENV__Header
{
    _cwmp__HoldRequests cwmp__HoldRequests;
    _cwmp__ID           *cwmp__ID;
};
