#!/bin/bash

print_help()
{
cat <<EOF
usage:  power_sw mask mode  (mask is 0xF, mode is on/off/rst)

EOF
exit 1
}

case "$2" in
    "rst" ) ACT="-ton" ;;
    "on"  ) ACT="-on" ;;
    "off" ) ACT="-off" ;;
    *     ) print_help ;;
esac

N=$(($1))
for I in `seq 1 4`; do
    if [ $((N & 1)) == 1 ];
    then
        /usr/local/bin/mp751 ${I} ${ACT}
    fi
    ((N /= 2))
done
