/* SPDX-License-Identifier: Apache-2.0 */
/** @file
 * @brief OVS Configuration Model TAPI
 *
 * Definition of test API for OVS configuration model
 * (doc/cm/cm_ovs.yml).
 *
 * Copyright (C) 2020-2022 OKTET Labs Ltd. All rights reserved.
 */

#ifndef __TE_TAPI_CFG_OVS_H__
#define __TE_TAPI_CFG_OVS_H__

#include "conf_api.h"
#include "te_kvpair.h"
#include "ovs_flow_rule.h"

#define TAPI_OVS_OTHER_CFG "other_config"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @defgroup tapi_conf_ovs PCI devices configuration of Test Agents
 * @ingroup tapi_conf
 * @{
 */

/** Configuration entry type, see tapi_cfg_ovs_cfg_name for details */
typedef enum tapi_cfg_ovs_cfg_type {
    TAPI_CFG_OVS_CFG_DPDK_ALLOC_MEM = 0,
    TAPI_CFG_OVS_CFG_DPDK_SOCKET_MEM,
    TAPI_CFG_OVS_CFG_DPDK_LCORE_MASK,
    TAPI_CFG_OVS_CFG_DPDK_HUGEPAGE_DIR,
    TAPI_CFG_OVS_CFG_DPDK_SOCKET_LIMIT,
    TAPI_CFG_OVS_CFG_DPDK_EXTRA,

    TAPI_CFG_OVS_CFG_DPDK_NTYPES, /**< Defines number of valid types */
} tapi_cfg_ovs_cfg_type;

/**
 * Configuration entry name. Names correspond to Open vSwitch configuration
 * entries.
 */
extern const char *const tapi_cfg_ovs_cfg_name[];

/** Open vSwitch Configuration entry array */
typedef struct tapi_cfg_ovs_cfg {
    char *values[TAPI_CFG_OVS_CFG_DPDK_NTYPES];
} tapi_cfg_ovs_cfg;

/**
 * Convert raw DPDK EAL arguments into Open vSwitch configuration entries.
 *
 * @param[in]  argc     Number of arguments
 * @param[in]  argv     EAL arguments
 * @param[out] ovs_cfg  Open vSwitch configuraion
 *
 * @return Status code
 */
extern te_errno tapi_cfg_ovs_convert_eal_args(int argc, const char *const *argv,
                                              tapi_cfg_ovs_cfg *ovs_cfg);

/**
 * Find the name of the OvS bridge that's running on the given agent.
 * This function assumes there is only one bridge. The memory for the name is
 * allocated by this function and needs to be freed by the user.
 *
 * @param[in]  ta       Test Agent name.
 * @param[out] bridge   Where the bridge name should be stored.
 *
 * @return Status code.
 */
extern te_errno tapi_cfg_ovs_default_bridge(const char *ta, char **bridge);

/**
 * Remove all flow rules from the given OvS bridge.
 * Only flow rules that are visible to TE will be removed, all hidden flows
 * will still be present after this function is called.
 *
 * @param[in]  ta       Test Agent name.
 * @param[in]  bridge   Bridge name. If NULL, use default bridge.
 *
 * @return Status code.
 */
extern te_errno tapi_cfg_ovs_clear_rules(const char *ta, const char *bridge);

/**
 * Add a flow rule to the given OvS bridge.
 * Flow cookie will be generated by the function and may be used by the user
 * to refer to the rule later.
 *
 * @param[in]  ta       Test Agent name.
 * @param[in]  bridge   Bridge name. If NULL, use default bridge.
 * @param[out] cookie   Where to store the new flow's cookie.
 * @param[in]  fmt      Format string that defines the flow rule.
 * @param[in]  ...      Additional arguments for the format string.
 *
 * @return Status code.
 */
extern te_errno tapi_cfg_ovs_add_rule(const char *ta, const char *bridge,
                                      uint64_t *cookie, const char *fmt, ...)
                                      __attribute__((format(printf, 4, 5)));

/**
 * Get the descriptor structure for the flow rule defined by the given
 * Open vSwitch bridge and cookie.
 *
 * @param[in]  ta       Test Agent name.
 * @param[in]  bridge   Bridge name. If NULL, use default bridge.
 * @param[in]  cookie   Flow cookie.
 * @param[out] rule     Flow rule descriptor structure.
 *
 * @return Status code.
 */
extern te_errno tapi_cfg_ovs_flow_rule_get(const char *ta, const char *bridge,
                                           uint64_t cookie,
                                           ovs_flow_rule *rule);

/**
 * Remove a flow rule from the given OvS bridge.
 *
 * @param[in]  ta       Test Agent name.
 * @param[in]  bridge   Bridge name. If NULL, use default bridge.
 * @param[out] cookie   Cookie of the flow to be removed.
 *
 * @return Status code.
 */
extern te_errno tapi_cfg_ovs_del_rule(const char *ta, const char *bridge,
                                      uint64_t cookie);

/**@} <!-- END tapi_conf_ovs --> */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* !__TE_TAPI_CFG_OVS_H__ */
