#!/usr/bin/env lua

local co = require("co")

local c1    = co.chunk(co.manager(2 ^ 20), io.stdout, 0)
local c3    = c1:fork_next()
local c2    = c3:fork_prev()

c1:write("xxx\n"):finish()
c3:write("zzz\n"):finish()
c2:write("yyy\n"):finish()
c1:finish()
c3:finish()
c2:finish()
