#!/usr/bin/env lua
---
-- Report generation tool - timestamp module test.
--
-- Copyright (C) 2010 Test Environment authors (see file AUTHORS in the
-- root directory of the distribution).
-- 
-- Test Environment is free software; you can redistribute it and/or
-- modify it under the terms of the GNU General Public License as
-- published by the Free Software Foundation; either version 2 of
-- the License, or (at your option) any later version.
-- 
-- Test Environment is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
-- 
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place, Suite 330, Boston,
-- MA  02111-1307  USA
-- 
-- @author Nikolai Kondrashov <Nikolai.Kondrashov@oktetlabs.ru>
-- 
-- @release $Id: train.lua 64325 2010-05-18 08:38:55Z knu $
--

require("strict")
local rgt   = {}
rgt.ts      = require("rgt.ts")

assert(rgt.ts(0, 0):format_short_rel() ==
       "00:00:00   0 ms")
assert(rgt.ts(0, 0):format_short_abs() ==
       "03:00:00   0 ms")
assert(rgt.ts(24 * 60 * 60, 0):format_short_abs() ==
       "03:00:00   0 ms")
assert(rgt.ts(23 * 60 * 60 + 59 * 60 + 59, 10 ^ 6 - 1):format_short_rel() ==
       "23:59:59 999 ms")
assert((rgt.ts(24 * 60 * 60, 0) - rgt.ts(0, 1)):format_short_rel() ==
       "23:59:59 999 ms")
assert((rgt.ts(10, 20000) - rgt.ts(5, 30000)):format_short_rel() ==
       "00:00:04 990 ms")
