#!/bin/sh
# the next line restarts using tclsh \
exec tclsh "$0" "$@"

source "test41.tcl"
source "test_gen.tcl"

set test_cases_pass [list \
    "pkg"     11          \
    "session" 11          \
    "test"    4           \
    "test"    10          \
    "test"    11          \
]

set test_cases_fail [list \
    "pkg"     4           \
    "pkg"     5           \
    "pkg"     10          \
    "session" 3           \
    "session" 4           \
    "session" 5           \
    "session" 10          \
    "test"    1           \
    "test"    3           \
]

foreach { node duration } $test_cases_pass {
    check_rgt_duration_filter $node $duration "pass"
}

foreach { node duration } $test_cases_fail {
    check_rgt_duration_filter $node $duration "fail"
}
