#!/bin/sh
# the next line restarts using tclsh \
exec tclsh "$0" "$@"

source "test9.tcl"

# Include everything but from user A, B and C.
set test_cases_pass [list \
    "A"   "CA"          \
    "A"   "AS"          \
    ""    "BB"          \
    ""    ""            \
    "ABS" "B1"          \
    "T" "Tester"        \
    "Teste" "C1"        \
]

set test_cases_fail [list \
    "Tester" "A"      \
    "Tester" "B"      \
    "Tester" "C"      \
    "A"      "B"      \
    "A"      "A"      \
    "C"      "C"      \
    ""       "B"      \
]

set any_log_level 1
source "test_gen.tcl"
