#!/bin/sh
# the next line restarts using tclsh \
exec tclsh "$0" "$@"

source "test19.tcl"

set test_cases_pass [list \
    "Tester" "Control"    \
    "A"      "Control"    \
    "ANY"    "Control"    \
    ""       "Control"    \
]

set test_cases_fail [list \
    "A"   "B"         \
    "A"   ""          \
    "Tester" ""       \
]

set any_log_level 1
source "test_gen.tcl"
