#!/bin/sh
# the next line restarts using tclsh \
exec tclsh "$0" "$@"

source "test41.tcl"
source "test_gen.tcl"

set test_cases_pass [list \
    "PACKAGE" 11          \
    "SESSION" 11          \
    "TEST"    4           \
    "TEST"    10          \
    "TEST"    11          \
]

set test_cases_fail [list \
    "PACKAGE" 4           \
    "PACKAGE" 5           \
    "PACKAGE" 10          \
    "SESSION" 3           \
    "SESSION" 4           \
    "SESSION" 5           \
    "SESSION" 10          \
    "TEST"    1           \
    "TEST"    3           \
]

foreach { node duration } $test_cases_pass {
    check_rgt_duration_filter $node $duration "pass"
}

foreach { node duration } $test_cases_fail {
    check_rgt_duration_filter $node $duration "fail"
}
