#!/bin/sh
# the next line restarts using tclsh \
exec tclsh "$0" "$@"

source "test42.tcl"
source "test_gen.tcl"

set test_cases_pass [list \
    "PACKAGE" 11          \
    "PACKAGE" 19          \
    "PACKAGE" 41          \
    "PACKAGE" 49          \
    "SESSION" 11          \
    "SESSION" 19          \
    "SESSION" 20          \
    "SESSION" 21          \
    "SESSION" 39          \
    "SESSION" 40          \
    "SESSION" 41          \
    "SESSION" 49          \
    "TEST"    4           \
    "TEST"    9           \
    "TEST"    10          \
    "TEST"    11          \
    "TEST"    19          \
    "TEST"    20          \
    "TEST"    21          \
    "TEST"    39          \
    "TEST"    40          \
    "TEST"    41          \
    "TEST"    49          \
]

set test_cases_fail [list \
    "PACKAGE" 3           \
    "PACKAGE" 4           \
    "PACKAGE" 5           \
    "PACKAGE" 10          \
    "PACKAGE" 20          \
    "PACKAGE" 25          \
    "PACKAGE" 40          \
    "PACKAGE" 50          \
    "PACKAGE" 51          \
    "SESSION" 3           \
    "SESSION" 4           \
    "SESSION" 5           \
    "SESSION" 10          \
    "SESSION" 50          \
    "SESSION" 60          \
    "TEST"    1           \
    "TEST"    3           \
    "TEST"    50          \
    "TEST"    51          \
]

foreach { node duration } $test_cases_pass {
    check_rgt_duration_filter $node $duration "pass"
}

foreach { node duration } $test_cases_fail {
    check_rgt_duration_filter $node $duration "fail"
}
