#!/bin/sh
# the next line restarts using tclsh \
exec tclsh "$0" "$@"

source "test13.tcl"

# First check that "Tester" "A" messages pass with any log level
set test_cases_pass [list \
    "Tester" "A"          \
]

set any_log_level 1
source "test_gen.tcl"

# Check that this group of records pass when log level not VERB,
# and fail when log level VERB
set test_cases_pass_not_verb [list \
    "Tester" "ANY"        \
    "ANY"    "A"          \
    "ANY"    "ANY"        \
]

foreach { level } $all_log_levels {
  set exp_result "pass"
  if {[string compare $level "VERB"] == 0} {
      set exp_result "fail"
  }

  foreach { entity user } $test_cases_pass_not_verb {
      check_rgt_entity_filter $entity $user $level $exp_result
  }
}
