#!/bin/sh
# the next line restarts using tclsh \
exec tclsh "$0" "$@"

source "test5.tcl"

set test_cases_pass [list \
    "Tester" "FlowNoRGT"  \
    "A"      "Self"       \
    ""       "Self"       \
    "ABS"    "Self"       \
]

set test_cases_fail [list \
    "A"   "B"         \
    "A"   ""          \
    ""    "B"         \
    ""    ""          \
    "ABA" "BBB"       \
    "Logger" "Self"   \
    "Tester" "Self"   \
    "Tester" "ABS"    \
    "Tester" ""       \
]

set any_log_level 1
source "test_gen.tcl"
