#!/bin/sh
# the next line restarts using tclsh \
exec tclsh "$0" "$@"

source "test2.tcl"

# The fileter should include everything
set test_cases_pass [list \
    "A"   "B"        \
    "A"   ""         \
    ""    "B"        \
    ""    ""         \
    "ABA" "BBB"      \
]

set any_log_level 1
source "test_gen.tcl"
