#!/bin/sh
# the next line restarts using tclsh \
exec tclsh "$0" "$@"

source "test40.tcl"
source "test_gen.tcl"

set test_cases_pass [list \
    "PACKAGE" 11          \
    "PACKAGE" 39          \
    "PACKAGE" 40          \
    "PACKAGE" 41          \
    "SESSION" 1           \
    "SESSION" 10          \
    "SESSION" 11          \
    "SESSION" 40          \
    "SESSION" 41          \
    "TEST"    20          \
    "TEST"    39          \
]

set test_cases_fail [list \
    "PACKAGE"  9          \
    "PACKAGE" 10          \
    "TEST"    40          \
    "TEST"    41          \
]

foreach { node duration } $test_cases_pass {
    check_rgt_duration_filter $node $duration "pass"
}

foreach { node duration } $test_cases_fail {
    check_rgt_duration_filter $node $duration "fail"
}
