#!/bin/sh
# the next line restarts using tclsh \
exec tclsh "$0" "$@"

source "test20.tcl"

set test_cases_pass [list \
    "A"   "B"             \
    "A"   "C"             \
    "AA"  "B"             \
    "ABC" "C"             \
    "A*"  "B"             \
    "A23" "C"             \
]

set test_cases_fail [list \
    "A" "D"               \
    "A" "BB"              \
    "BA" "B"              \
    "BA" "C"              \
    "REST" ""             \
]

set any_log_level 1
source "test_gen.tcl"
