#!/bin/sh
# the next line restarts using tclsh \
exec tclsh "$0" "$@"

source "test8.tcl"

set test_cases_pass [list \
    "A"   "C"         \
    "A"   ""          \
    ""    "B"         \
    ""    ""          \
    "ABS" "BBB"       \
    "T" "Tester"      \
    "Teste" "C"       \
]

set test_cases_fail [list \
    "Tester" "ABC"  \
    "Tester" "B"    \
    "Tester" ""     \
    "A"    "B"      \
]

set any_log_level 1
source "test_gen.tcl"
