#! /bin/sh
#
# Test Environment 
# 
# TE_GCC -- a wrapper around GCC to perform TCE with gcov
#
# Copyright (C) 2005 Test Environment authors (see file AUTHORS in the 
# root directory of the distribution).
#
# Test Environment is free software; you can redistribute it and/or 
# modify it under the terms of the GNU General Public License as 
# published by the Free Software Foundation; either version 2 of 
# the License, or (at your option) any later version.
# 
# Test Environment is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
# MA  02111-1307  USA
#
# Author Artem V. Andreev <Artem.Andreev@oktetlabs.ru>
# 
# $Id$

coverage_options=
processed_options=
for arg in $@; do
    case "$arg" in
        -c) TCE_BBHOOK_O=""
        processed_options="$processed_options -c"
        -O*|-g|-ftest-coverage|-fprofile-arcs) ;;         
        -*) processed_options="$processed_options $arg"
        *) mydir=`dirname $arg`
           myself=`basename $arg`
           fullpath=`cd $mydir; echo $PWD`/$myself
           for tce in ${TCE_SRC}; do
              case "$fullpath" in
                 $tce*)
                 coverage_options="-g -ftest-coverage -fprofile-arcs"
                 ;;
              esac
           done   
           processed_options="$processed_options $arg"
           ;;
    esac
done

exec ${TCE_CC} $coverage_options $processed_options $TCE_BBHOOK_O