#! /bin/sh


if test -e ${TE_BUILD}/builder.conf.processed ; then
    . ${TE_BUILD}/builder.conf.processed
fi    

for i in ${TE_BS_NUTS} ${TE_BS_NUTLIBS}; do 
    tce_taname=`eval echo '$NUT_'$i'_TCE_TANAME'` ; 
    if test -n "${tce_taname}" ; then 
        NUT_SOURCES=`eval echo '$NUT_'$i'_SOURCES'` 
        echo "*** Test coverage report for $i:"
        find $NUT_SOURCES -name '*.gcov' -exec rm -f '{}' ';'
        log2da ${tce_taname} <"$1" && find $NUT_SOURCES -name '*.da' -exec tce_gcov '{}' ';' && \
            find $NUT_SOURCES -name '*.gcov' -exec cat '{}' ';'
    fi        
done



