#! /bin/sh
#
# Test Environment 
# 
# TE_GCC -- a wrapper around GCC to perform TCE with gcov
#
# Copyright (C) 2005 Test Environment authors (see file AUTHORS in the 
# root directory of the distribution).
#
# Test Environment is free software; you can redistribute it and/or 
# modify it under the terms of the GNU General Public License as 
# published by the Free Software Foundation; either version 2 of 
# the License, or (at your option) any later version.
# 
# Test Environment is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
# MA  02111-1307  USA
#
# Author Artem V. Andreev <Artem.Andreev@oktetlabs.ru>
# 
# $Id$

coverage_options=
for arg in $@; do
    case "$arg" in
      -*) ;;
      *) for tce in ${TCE_SRC}; do
            if test "x$arg" = "x$tce"; then
                coverage_options="-g -ftest-coverage -fprofile-arcs"
            fi
         done
         ;;
    esac
done

if test -n "$coverage_options"; then
    bbhook=${TE_BUILD}/engine/builder/coverage/bbhook.o
    for arg in $@; do
        case "$arg" in
            -c) bbhook=""; processed_options="$processed_options -c" ;;
            -O[1-9]|-O|-g|-ftest-coverage|-fprofile-arcs) ;;         
            *) processed_options="$processed_options $arg" ;;
        esac
    done
else
    processed_options="$@"
fi

exec ${TE_CC} -g -ftest-coverage -fprofile-arcs $processed_options $bbhook