#! /bin/sh

cat <<EOF
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
<HEAD>
  <META HTTP-EQUIV="CONTENT-TYPE" CONTENT="text/html; charset=utf-8">
  <TITLE>TCE Summary</TITLE>
</HEAD>
<BODY LANG="en-US" DIR="LTR">
<H1 ALIGN=CENTER>TCE Summary</H1>
<H2>`grep "Grand Total" $1`
<TABLE BORDER=1 CELLPADDING=4 CELLSPACING=3>
<TH>% of taken branches</TH>
<TH>Total branches</TH>
<TH>Source file</TH>
EOF

awk  '/^[0-9]+\.[0-9]+% of[[:space:]]*[0-9]+ branches of code taken/ { printf "%s %s %s ", $1, $3, $NF }
      /^=== / { print $2; }' $1 | 
    sort -k1,1g -k2,2nr | 
    awk '$2 != 0 { printf "<tr><td>%s<td>%s<td><a href=\"#%s\">%s</a></tr>\n", $1, $2, $4, $3 }'

echo "</TABLE>"

awk '/^\*\*\*|[[:space:]]*-:[[:space:]]*0:/ { next }
     /^======/ { print "</pre>"; next } 
     /^=== / { printf "<p><a name=\"%s\"></a>\n", $2; next }
     /^[0-9]+\.[0-9]+% of[[:space:]]*[0-9]+ lines/ { printf "<h2>%s</h2>\n<p>\n<pre>", $NF }
     { gsub(/&/, "\\&amp;"); gsub(/</, "\\&lt;"); gsub(/>/, "\\&gt;"); gsub(/"/, "\\&quot;"); print }' $1
     
     