#! /bin/sh

tce_taname=$1 
mergefile=$2
outfile=${mergefile}.new
if test -n "$3"; then
    TE_BUILD=$3
    NUT_SOURCES=$4
elif test -e ${TE_BUILD}/builder.conf.processed ; then
    . ${TE_BUILD}/builder.conf.processed
    NUT=`eval echo '$TCE_TANAME_'$tce_taname'_NUT'`
    if test -n "$NUT"; then
        NUT_SOURCES=`eval echo '$NUT_'$NUT'_SOURCES'` 
    fi
fi    



if test -n "$NUT_SOURCES"; then
    echo "*** Test coverage report for $tce_taname:" >$outfile
    find $NUT_SOURCES \( -name '*.gcov' -o -name '*.da' \) -exec rm -f '{}' ';'
        tar -x -P -f ${TE_BUILD}/tce_${tce_taname}.tar
        (find $NUT_SOURCES \( -name '*.da' -o -name '.[a-z]*.da' \) -exec tce_gcov '{}' ';' && \
            find $NUT_SOURCES -name '*.gcov' -exec tce_merge $mergefile '{}' ';') >> $outfile
        echo >>$outfile
        tce_count $outfile '^branch[[:space:]]*[0-9]+ never executed' '^branch[[:space:]]*[0-9]+ taken' | 
        (
            read ratio sum
            echo "*** Grand Total: $ratio% of $sum branches covered" >>$outfile
        )
        if test -f $mergefile; then
            mv -f $mergefile $mergefile.prev
        fi
        mv -f $outfile $mergefile
fi        





