#! /bin/sh

cd `dirname "$1"`
objname=`basename "$1" .da`.o
objname=${objname#.tmp_}
for file in `objdump -l -d "$objname" | sed -e '/^.*\.c:[0-9][0-9]*$/s/:[0-9][0-9]*$//
t
d' | sort | uniq`; do
  cd `dirname $file`
  gcov -c -b -o "$1" `basename $file` >/dev/null
done
