#! /bin/sh


if test -e ${TE_BUILD}/builder.conf.processed ; then
    . ${TE_BUILD}/builder.conf.processed
fi    

tce_taname=$1 
outfile=$2
NUT=`eval echo '$TCE_TANAME_'$tce_taname'_NUT'`

if test -n "$NUT"; then
    NUT_SOURCES=`eval echo '$NUT_'$NUT'_SOURCES'` 
    echo "*** Test coverage report for $i:" >$outfile
    find $NUT_SOURCES \( -name '*.gcov' -o -name '*.da' \) -exec rm -f '{}' ';'
        tar -x -P -f ${TE_BUILD}/tce_${tce_taname}.tar
        (find $NUT_SOURCES -name '*.da' -exec tce_gcov '{}' ';' && \
            find $NUT_SOURCES -name '*.gcov' -exec cat '{}' ';') >> $outfile
        non_execed=`grep '^[[:space:]]*##*:' $outfile | wc | awk '{ print $1 }'`
        execed=`grep '^[[:space:]]*[0-9][0-9]*:' $outfile | wc | awk '{ print $1 }'`
        echo >>$outfile
        echo "*** Grand Total: `expr $execed \* 100 / \( $non_execed + $execed \)`% covered" >>$outfile
fi        




