#! /bin/sh

usage () 
{
    cat >&2 <<EOF
USAGE: tce_summary <log-file-name> [<options>...] [<output-file>]
Converts a TCE log into HTML form. If <output-file> is not given,
standard output is assumed.

Options:
--datadir=<directory>  If given, <output-file> will only contain
                        an index of files, actual annotated sources
                        being placed into <directory>, one file per source
--sort-by=<MODE>       The mode of sorting the index of files:
                            branches  by covered branches percentage
                                      (the default)
                            lines     by covered lines percentage
                            sources   by filename

EOF
exit 0
}

outputfile="/dev/stdout"
sortmode='sort -k3,3g -k4,4nr'
for arg; do
    case "$arg" in
        --datadir=*) datadir=${arg#--datadir=}/; mkdir $datadir 
            ;;
        --sort-by=branches) sortmode='sort -k3,3g -k4,4nr' ;;
        --sort-by=lines) sortmode='sort -k1,1g -k2,2nr' ;;
        --sort-by=sources) sortmode='sort -k5,5' ;;
        --help) usage ;;
        --*) echo "Unrecognized option $arg" >&2; usage; exit 1 ;;
        *) 
        if test -z "$sourcefile"; then
            sourcefile="$arg"
        else
            outputfile="$arg"
        fi
        ;;
    esac
done

if test -z "$sourcefile"; then
    echo "Log file name must be given" >&2
    usage
    exit 1
fi

cat >$outputfile <<EOF
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
<HEAD>
  <META HTTP-EQUIV="CONTENT-TYPE" CONTENT="text/html; charset=utf-8">
  <TITLE>TCE Summary</TITLE>
</HEAD>
<BODY LANG="en-US" DIR="LTR">
<H1 ALIGN=CENTER>TCE Summary</H1>
`grep "Grand Total" $sourcefile | sed 's/\*//g
s/^/<H2>/
s/$/<\/H2>/
'`
<TABLE BORDER=1 CELLPADDING=4 CELLSPACING=3>
<TH>% of taken branches</TH>
<TH>Total branches</TH>
<TH>% of executed lines</TH>
<TH>Total lines</TH>
<TH>Source file</TH>

EOF

awk '/^[0-9]+\.[0-9]+% of[[:space:]]*[0-9]+ lines of code executed/ { printf "%s %s ", $1, $3}
    /^[0-9]+\.[0-9]+% of[[:space:]]*[0-9]+ branches of code taken/ { printf "%s %s %s ", $1, $3, $NF }
    /^=== / { print $2; }' $sourcefile | 
    $sortmode |
    awk -vSUBDIR=$datadir \
        '$2 != 0 { fname=$5; gsub(/\//, "-", fname);
                   printf "<tr><td>%s<td>%s<td>%s<td>%s<td><a href=\"%s\">%s</a></tr>\n", 
                   $3, $4, $1, $2, (SUBDIR ? SUBDIR fname ".html" : "#" $6) , $5 }' >>$outputfile

echo "</TABLE>" >>$outputfile

if test -n "$datadir"; then
    echo "</BODY>" >>$outputfile
    echo "</HTML>" >>$outputfile
fi

awk -vSUBDIR=$datadir ' BEGIN { myfile = "/dev/stdout" } 
      /^\*\*\*|[[:space:]]*-:[[:space:]]*0:/ { next }
      /^======/ { print "</pre>" >>myfile; 
                  if (SUBDIR) {
                     print "</body>" >>myfile
                     print "</html>" >>myfile
                     close(myfile)
                  }
                  next } 
      /^=== / { 
          if (SUBDIR) {
             name=filename
             gsub(/\//, "-", name)
             myfile=SUBDIR name ".html"
             print "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">" >myfile
             print "<HTML>" >>myfile
             print "<HEAD>" >>myfile
             print "<META HTTP-EQUIV=\"CONTENT-TYPE\" CONTENT=\"text/html; charset=utf-8\">" >>myfile
             print "<TITLE>TCE Annotated Source for " filename "</TITLE>" >>myfile
             print "</HEAD>" >>myfile
             print "<BODY LANG=\"en-US\" DIR=\"LTR\">" >>myfile
          }
          printf "<h2>%s</h2>\n", filename >> myfile
          printf "<p><a name=\"%s\"></a>\n<pre>", $2 >> myfile
          print header >> myfile
          header = ""
          next
      }
      /^[0-9]+\.[0-9]+%/ { 
          filename=$NF
          header=header $0 "\n"
          next
      }
      { gsub(/&/, "\\&amp;"); gsub(/</, "\\&lt;"); gsub(/>/, "\\&gt;"); gsub(/"/, "\\&quot;"); print >> myfile}' $sourcefile >>$outputfile

     
     