#! /bin/sh

# Test Environment
#
# Script for building of the one NUT.
#
# Copyright (C) 2004 Test Environment authors (see file AUTHORS in the 
# root directory of the distribution).
#
# Test Environment is free software; you can redistribute it and/or 
# modify it under the terms of the GNU General Public License as 
# published by the Free Software Foundation; either version 2 of 
# the License, or (at your option) any later version.
# 
# Test Environment is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
# MA  02111-1307  USA
#
# Author Elena Vengerova <Elena.Vengerova@oktet.ru>
# 
# $Id$
#

NUT=$1
NUT_SOURCES=$2
NUT_PARMS=$3

if test -e builder.conf.processed ; then
    . builder.conf.processed
fi    

mkdir -p ${TE_INSTALL_NUT} 

if test -z "${NUT_SOURCES}" ; then
    NUT_SOURCES=`eval echo '$NUT_'$NUT'_SOURCES'` 
fi    

NUT_SCRIPT=`eval echo '$NUT_'$NUT'_SCRIPT'` 
if test -z"${NUT_SCRIPT}" ; then
    NUT_SCRIPT=${NUT_SOURCES}/te_build_nut
fi    

if test -z "${NUT_PARMS}" ; then
    NUT_PARMS=`eval echo '$NUT_'$NUT'_PARMS'` 
fi    
    
NUT_ST_LOCATION=`eval echo '$NUT_'$NUT'_ST_LOCATION'`
NUT_ST_STRING=`eval echo '$NUT_'$i'_ST_STRING'` 

if test -n "`eval echo '$NUT_'$NUT'_TCE_TANAME'`" ; then 
    TCE_SRC=`eval echo '$NUT_'$NUT'_TCE_SOURCES'`     
    if test -z "$TCE_SRC"; then
        tce_src=$NUT_SOURCES
    else
        tce_src=
        for i in $TCE_SRC; do
            tce_src="$tce_src $NUT_SOURCES/$i"
        done
    fi
    export TCE_SRC=$tce_src
    export TCE_CC=`eval echo '$NUT_'$NUT'_TCE_CC'`
    export TCE_CFLAGS=`eval echo '$NUT_'$NUT'_TCE_CFLAGS'`
    if test -z "${TCE_CC}" ; then
        export TCE_CC=${CC:-gcc}
    fi
    export CC=`which tce_gcc`
    export CLINK=`which tce_gcc`
    libpath=`dirname $CC`/../lib
    export TCE_BBHOOK_O=$libpath/bbhook.o
    export TCE_LOGFORK="-lpthread -L$libpath -llogfork -lloggerta"
    ${TCE_CC} -c -o $TCE_BBHOOK_O ${TCE_CFLAGS} -I${TE_BASE}/include \
        -I${TE_BASE}/lib/logfork -I${TE_BASE}/lib/loggerta \
        -I${TE_BUILD}/include \
        ${TE_BASE}/engine/builder/coverage/bbhook.c || exit 1 
fi 

TE_INSTALL=${TE_INSTALL} TE_INSTALL_NUT=${TE_INSTALL_NUT} ${NUT_SCRIPT} ${NUT} ${NUT_PARMS} 
NUT_SCRIPT_RC=$? 

exit ${NUT_SCRIPT_RC}
