#! /bin/sh

# Test Environment
#
# Script for building of test suites
#
# Copyright (C) 2003 Test Environment authors (see file AUTHORS in the 
# root directory of the distribution).
#
# Test Environment is free software; you can redistribute it and/or 
# modify it under the terms of the GNU General Public License as 
# published by the Free Software Foundation; either version 2 of 
# the License, or (at your option) any later version.
# 
# Test Environment is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
# MA  02111-1307  USA
#
# Author Elena Vengerova <Elena.Vengerova@oktet.ru>
# 
# $Id: $
#

if test -n "$SUITE_SOURCES" ; then
    pushd ${SUITE_SOURCES} >/dev/null
    if test -e configure.ac ; then 
        if test ! -e configure ; then
            aclocal || exit 1 ;
            autoconf || exit 1 ;
            automake || exit 1 ;
        fi
    fi
    popd >/dev/null
    if test -n "${TE_BUILD}" ; then
        cd ${TE_BUILD} ; 
        make suite || exit 1 ;
    else 
        cd ${SUITE_SOURCES} ;
        mkdir -p ${TE_INSTALL_SUITE} ;
        if test ! -e Makefile ; then 
            TE_CFLAGS="-Wall -I${TE_INSTALL}/include \
                       -I${TE_INSTALL}/${HOST}/include" \
            TE_LDFLAGS="-L${TE_INSTALL}/${HOST}/lib" \
            ./configure --prefix=${TE_INSTALL_SUITE} || exit_with_log ;
        fi ;
        make install || exit 1 ;
    fi
fi
