#! /bin/sh
#
# Windows Test Agent
# Calculates some variables for the Windows platform
# Script is inserted from te_build_win_app and te_build_win_lib
#     
# Copyright (C) 2006 Test Environment authors (see file AUTHORS in
# the root directory of the distribution).
#
# Test Environment is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# Test Environment is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA  02111-1307  USA
#
#
# Author: Elena Vengerova <Elena.Vengerova@oktetlabs.ru>
#
# $Id:  $
#

if test $PLATFORM != ${PLATFORM#x86_64} ; then

DIR_POSTFIX=64
PATH_POSTFIX=/win64/x86/AMD64
LIB_POSTFIX="\\AMD64"
ADD_LIB="bufferoverflowU.lib"

else

DIR_POSTFIX=32
PATH_POSTFIX=
LIB_POSTFIX=
ADD_LIB=

fi

if test -n "$TE_WIN32_BUILD_HOST_KEY" ; then
    KEY="-i $TE_WIN32_BUILD_HOST_KEY "
fi    

