#! /bin/sh
#
# Test Environment Builder
#
# Script for building of NUT libraries and images
# Usage: te_build_nut <configuration file>
#
# Copyright (C) 2004 Test Environment authors (see file AUTHORS in
# the root directory of the distribution).
#
# Test Environment is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# Test Environment is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA  02111-1307  USA
#
#
# Author Elena Vengerova <Elena.Vengerova@oktet.ru>
#
# $Id$
#

PARSER=`dirname $0`/../share/te_builder/nut.m4
cat $PARSER $1 | m4 > ${TE_TMP}/nut.conf.processed
. ${TE_TMP}/nut.conf.processed

DEF_CC=$CC
DEF_CXX=$CXX

mkdir -p ${TE_INSTALL_NUT}
for i in $NUTS ; do
    NUT_SOURCES=`eval echo '$NUT_'$i'_SOURCES'`
    NUT_SCRIPT=`eval echo '$NUT_'$i'_SCRIPT'`
    NUT_PARMS=`eval echo '$NUT_'$i'_PARMS'`
    TCE_SRC=`eval echo '$NUT_'$i'_TCE_SRC'`
    TA=`eval echo '$NUT_'$i'_TCE_TA'`
    export TE_INSTALL_NUT=${TE_INSTALL_NUT}
    export TCE_SRC
    if test -z "$TA" ; then
        export CC=$DEF_CC
        export CXX=$DEF_CXX
    else
        export CC=`which tce_gcc`
        export CXX=`which tce_gxx`
    fi
    ${NUT_SCRIPT} ${NUT} ${NUT_PARMS} || exit 1
done

exit 0
