#! /bin/bash
#
# Windows Test Agent
# Calculates some variables for the Windows platform
# Script is inserted from te_build_win_app and te_build_win_lib
#     
# Copyright (C) 2003-2018 OKTET Labs.
#
# Author: Elena Vengerova <Elena.Vengerova@oktetlabs.ru>
#
# $Id:  $
#

if test $PLATFORM != ${PLATFORM%64} ; then

DIR_POSTFIX=64
PATH_POSTFIX=/win64/x86/AMD64
LIB_POSTFIX="\\AMD64"
ADD_LIB="bufferoverflowU.lib"

else

DIR_POSTFIX=32
PATH_POSTFIX=
LIB_POSTFIX=
ADD_LIB=

fi

if test -n "$TE_WIN32_BUILD_HOST_KEY" ; then
    KEY="-i $TE_WIN32_BUILD_HOST_KEY "
fi    

