#! /bin/sh
#
# Windows Test Agent
# Build library using native compiler
# Agruments: 
#     source directory
#     platform
#     library name
#     installation prefix for the platform
#     list of source files (basenames only)
#     
# Copyright (C) 2006 Test Environment authors (see file AUTHORS in
# the root directory of the distribution).
#
# Test Environment is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# Test Environment is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA  02111-1307  USA
#
#
# Author: Elena Vengerova <Elena.Vengerova@oktetlabs.ru>
#
# $Id:  $
#

SRCDIR=$1
PLATFORM=$2
LIBNAME=$3
INCLUDE=$4/include
shift 4

. `dirname $0`/te_build_win_platform

WIN_DIR=${USER}_build_${LIBNAME%%.lib}_$DIR_POSTFIX

if test -z "$TE_WIN32_BUILD_HOST" ; then
    echo "Warning: build host for $PLATFORM platform is not specified; \
          library $LIBNAME is not (re-)built"
    touch ${LIBNAME}
    exit 0
fi

if ! ssh $KEY $TE_WIN32_BUILD_HOST \
         "rm -rf $WIN_DIR; mkdir $WIN_DIR" >/dev/null; then
    echo "Error: build host $TE_WIN32_BUILD_HOST is unreachable"
    exit 1
fi

rm -rf tmpsrc
mkdir tmpsrc
cd tmpsrc

# Apply pre-processor

for i in $* ; do 
    gcc -I${INCLUDE} -I${SRCDIR} -include te_win.h -DWINDOWS \
        -P -E ${SRCDIR}/${i} -o ${i}.tmp ; 
    cat ${i}.tmp | awk --posix '\
    /^INCLUDE/ { printf("#include <%s>\n", \
                 substr($1, 9, length($1) - 9)); next; } \
    { print $0; }'  > ${i} ; 
    rm ${i}.tmp ; 
    indent ${i} ;
done
rm -f *~

# Generate the script
cat >build.sh <<EOF
cd $WIN_DIR
MSSDK_CYGWIN_BAD=\$( cygpath -u \$MSSDK ) 
MSSDK_CYGWIN="\`echo \$MSSDK_CYGWIN_BAD\`"
export PATH="\${MSSDK_CYGWIN}/Bin$PATH_POSTFIX:\$PATH"
cl /nologo /w -D_WIN32_WINNT=0x0501 -D_CRT_SECURE_NO_DEPRECATE /Od *.c /c   
lib /OUT:${LIBNAME} /nologo *.obj
EOF
chmod a+x build.sh

# Build the library

scp $KEY * ${TE_WIN32_BUILD_HOST}:$WIN_DIR
cd ..
rm -rf tmpsrc 

ssh $KEY ${TE_WIN32_BUILD_HOST} "bash -l -c $WIN_DIR/build.sh"

scp $KEY ${TE_WIN32_BUILD_HOST}:$WIN_DIR/${LIBNAME} .

if test -e ${LIBNAME} ; then
    exit 0
fi

exit 1
