#! /bin/bash
#
# Test Environment Builder
#
# Script for logging of builder output
#
#
# Copyright (C) 2003-2018 OKTET Labs.
#
# Author Elena Vengerova <Elena.Vengerova@oktet.ru>
#
#

while read message ; do
    te_log_message Engine Builder "$message" ;
done ;
