#! /bin/bash
#
# Test Environment Builder
#
# Script for logging of builder output
#
#
# Copyright (C) 2004-2022 OKTET Labs.

while read message ; do
    te_log_message Engine Builder "$message" ;
done ;
