#! /bin/sh
#
# Test Environment Builder
#
# Script for creation of installation directories
#
#
# Copyright (C) 2004 Test Environment authors (see file AUTHORS in
# the root directory of the distribution).
#
# Test Environment is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# Test Environment is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA  02111-1307  USA
#
#
# Author Elena A. Vengerova <Elena.Vengerova@oktetlabs.ru>
#
# $Id$
#

pushd $1 >/dev/null
PREFIX=`pwd`
popd >/dev/null

if test -n "${TE_BUILD}" ; then
    cd ${TE_BUILD}
fi
if test -e builder.conf.processed ; then
    . builder.conf.processed
fi

for p in ${TE_BS_PLATFORMS} ; do
    PLATFORM=`eval echo '$'${p}'_PLATFORM'`
    mkdir -p $PREFIX/$PLATFORM
done

mkdir -p $PREFIX/agents

exit 0
