#! /bin/bash
#
# Test Environment Builder
#
# Script for calling make with specified target for cross packages
#
# Copyright (C) 2003-2018 OKTET Labs.
#
# Author Elena A. Vengerova <Elena.Vengerova@oktetlabs.ru>
#
# $Id: te_cross_build 15927 2005-07-08 06:25:10Z arybchik $
#

TARGET=$1

if test -e builder.conf.processed ; then
    . builder.conf.processed
else
    # Possibly we're called after distclean and builder.conf.processed
    # is removed - assume all libraries and agents as "cross". 
    for dir in lib agents ; do
        if ! test -e $dir ; then continue ; fi
        cd $dir
        for package in * ; do
            if ! test -d $package ; then continue ; fi
            cd $package
            if test -e Makefile ; then make $TARGET || exit 1 ; fi
            cd ..
        done
        cd ..
    done
    for dir in *include ; do
        if ! test -e $dir ; then continue ; fi
        cd $dir
        if test -e Makefile ; then make $TARGET || exit 1 ; fi
        cd ..
    done
    exit 0
fi    

for p in ${TE_BS_PLATFORMS} ; do
    if test $p = ${TE_HOST} ; then continue ; fi

    pushd platforms/${p}/include >/dev/null; 
    if test -e Makefile ; then make $TARGET || exit 1 ; fi
    popd >/dev/null

    LIBS=`eval echo '$'${p}'_LIBS'`
    for package in $LIBS ; do
        pushd platforms/${p}/lib/$package >/dev/null
        if test -e Makefile ; then make $TARGET || exit 1 ; fi
        popd >/dev/null
    done
done

DUMMY=

for package in $DUMMY $TE_BS_TA ; do
    PLATFORM=`eval echo '$TE_BS_TA_'${package}'_PLATFORM'` ;
    if test "$PLATFORM" = ${TE_HOST} ; then continue ; fi ;
    cd agents/$package
    if test -e Makefile ; then make $TARGET || exit 1 ; fi
    cd ../..
done

exit 0
