#! /bin/bash
#
# Test Environment Builder
#
# Script for creation of installation directories
#
#
# Copyright (C) 2004-2022 OKTET Labs.

[ -d $1 ] || mkdir -p $1
pushd $1 >/dev/null
PREFIX=`pwd`
popd >/dev/null

SCRIPT_DIR=`dirname $0`
. ${SCRIPT_DIR}/te_functions

if test -n "${TE_BUILD}" ; then
    cd ${TE_BUILD}
fi

if test -e builder.conf.processed ; then
    . builder.conf.processed
fi

for p in ${2:-${TE_BS_PLATFORMS}} ; do
    libs=${p}_EXT_LIBS
    dir=${p}_EXT_LIBS_DIR

    mkdir -p $PREFIX/$p
    if test ! -f "${TE_BUILD}/${p}.sbd"; then
        sbd="${TE_BUILD}"
    else
        sbd=$(cat "${TE_BUILD}/${p}.sbd")
    fi
    # Skip download if agent platform directory exists at install path
    # and at build path.
    te_eval_or_ssh "${p}" "
        [ -d \"$PREFIX/$p/lib\" -a -d \"${sbd}/platforms/$p/lib\" ] && exit 0 ;

        if [ \"${TE_EXT_LIBS}\" ] ; then
            mkdir -p \"${sbd}/platforms/$p/lib\" ;
            mkdir -p \"${sbd}/platforms/$p/include\" ;
            pushd \"${sbd}/platforms/$p/\" >/dev/null ;
            for i in ${!libs} ; do
                rm -rf \$i.tgz ;
                wget --no-verbose ${TE_EXT_LIBS}/${!dir}/\$i.tgz ;
                if [ \$? -eq 0 ] ; then
                    echo \"./$p/\$i.tgz \\\\\" >>${TE_EXT_LIBS_FILE} ;
                    tar -tzf \$i.tgz |
                        sed 's:\(.*\):./$p/\1 \\\\:' >>${TE_EXT_LIBS_FILE} ;
                    tar xzf \$i.tgz ;
                fi ;
            done ;
            popd >/dev/null ;
        fi
    "
done

mkdir -p $PREFIX/agents

exit 0
