#!/bin/bash
#
# Test Environment Builder
#
# Fix dangling links after relocation
#
# Copyright (C) 2016 Test Environment authors (see file AUTHORS in
# the root directory of the distribution).
#
# Test Environment is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# Test Environment is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA  02111-1307  USA
#
#
# @author Artem V. Andreev <Artem.Andreev@oktetlabs.ru>
#
# $Id$
#

BASEDIR="$1"
DESTROOT="$2"

shift 2

if test "${BASEDIR:0:1}" != "/"; then
    echo "${BASEDIR} is not an absolute path" >&2
    exit 1
fi

for name; do
    # Non-links and non-dangling links are skipped
    test -e "$name" && continue

    reltgt="$(readlink "$name")"
    newtgt="$(realpath -m -s "${BASEDIR}/${name#${DESTROOT}/}/../${reltgt}")"
    if test "${reltgt:0:1}" == "/" -o ! -e "${newtgt}"; then
        echo "warning: cannot fix '$reltgt' using ${newtgt} pointed to by '$name'" >&2
        continue
    fi
    ln -sf "${newtgt}" "$name" || exit 1
done
