#! /bin/sh
#
# Test Environment Builder
#
# Script for RPC functions table generation.
#
# Usage: builder_generate_rpctbl <tarpc.x.m4 file> [--generate-dummy]
#
# List of TA object may contain libraryies as well.
#
#
# Copyright (C) 2004 Test Environment authors (see file AUTHORS in
# the root directory of the distribution).
#
# Test Environment is free software; you can redistribute it and/or 
# modify it under the terms of the GNU General Public License as 
# published by the Free Software Foundation; either version 2 of 
# the License, or (at your option) any later version.
# 
# Test Environment is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
# MA  02111-1307  USA
#
#
# Author Elena A. Vengerova <Elena.Vengerova@oktetlabs.ru>
# 
# $Id$
#

cat >tmp <<EOF
changequote([,])
define([RPC_DEF], [\$1])
EOF

cat $1 | grep 'RPC_DEF(' >> tmp
FUNCS=`m4 tmp`

rm tmp

cat >>tarpc_xdr.c <<EOF
struct {
    char *name;
    void *rpc;
    void *in;
    int   in_arglen;
    void *out;
    int   out_arglen;
} rpc_functions[] = {
EOF

for i in $FUNCS ; do
    echo '    { "'$i'", _'$i'_1_svc,' >> tarpc_xdr.c
    echo '      xdr_tarpc_'$i'_in, sizeof(tarpc_'$i'_in),' >> tarpc_xdr.c
    echo '      xdr_tarpc_'$i'_out, sizeof(tarpc_'$i'_out) },' >> tarpc_xdr.c
done

echo '    { NULL, NULL, NULL, 0, NULL, 0 }' >> tarpc_xdr.c
echo '};' >> tarpc_xdr.c

if test "$2" == "--generate-dummy" ; then
    rm -f tarpc_dummy.c
    for i in $FUNCS ; do
        echo 'void _'$i'_1_svc() {}' >> tarpc_dummy.c
    done
fi
