#! /bin/bash
#
# Test Environment Builder
#
# Collection of meson-specific functions.
#
# Copyright (C) 2003-2020 OKTET Labs.
#

# Helper function to split ninja output into stdout and stderr
function ninja_status_filter () {
    local l n msg_install
    while read -r l; do
        n=${l#\[ninja\]}
        # For unknown reason ninja does not apply NINJA_STATUS variable
        # when installing files.
        msg_install=${l#Installing }
        test "$l" != "$n" -o "$l" != "$msg_install" \
            && printf "%s\n" "$n" || printf "%s\n" "$l" >&2
    done
}
