#! /bin/bash
#
# Helper script to build i386 binaries with meson
#
# Copyright (C) 2020 OKTET Labs.
#
# Author Damir Mansurov <Damir.Mansurov@oktetlabs.ru>
#

set -e

pkg_cfg_path="$(pkg-config --variable pc_path pkg-config)"
if test "${pkg_cfg_path/x86_64/}" != "${pkg_cfg_path}" ; then
    # Debian/Ubuntu
    export PKG_CONFIG_PATH="${pkg_cfg_path//x86_64/i386}"
elif test "${pkg_cfg_path/lib64/}" != "${pkg_cfg_path}" ; then
    # RHEL7, RHEL8, Fedora
    export PKG_CONFIG_PATH="${pkg_cfg_path//lib64/lib}"
else
    echo "ERROR: unknown PKG_CONFIG_PATH: $pkg_cfg_path" >&2
    exit 1
fi

export CPPFLAGS="-m32"
export LDFLAGS="-m32"
