#! /bin/sh
#
# RPC support
# Substitute RPC2H and H2RPC by proper code
#     
# Copyright (C) 2006 Test Environment authors (see file AUTHORS in
# the root directory of the distribution).
#
# Test Environment is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# Test Environment is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA  02111-1307  USA
#
#
# Author: Elena Vengerova <Elena.Vengerova@oktetlabs.ru>
#
# $Id:  $
#

cat $1 | awk --posix '\
/RPC2H/ { name=substr($1, 7, length($1) - 8); \
          printf("#ifdef %s\n        case RPC_%s: return %s;\n#endif\n", 
                 name, name, name); next } ; \
/H2RPC/ { name=substr($1, 7, length($1) - 8); \
          printf("#ifdef %s\n        case %s: return RPC_%s;\n#endif\n", 
                 name, name, name); next } ; \
{ print $0; }'  > $2 

exit 0