#! /bin/sh
#
# Test Environment Builder
#
# Script for generation of the list of unsupported RPC stubs on the TA.
#
# Usage: te_rpc_unsupported <tarpc.h pathname> 
#
#
# Copyright (C) 2004 Test Environment authors (see file AUTHORS in
# the root directory of the distribution).
#
# Test Environment is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# Test Environment is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA  02111-1307  USA
#
#
# Author Elena A. Vengerova <Elena.Vengerova@oktetlabs.ru>
#
# $Id: te_rpc_supported 17303 2005-08-18 14:05:30Z helen $
#

cat $1 | awk --posix '\
/1_svc/ { name=substr($3, 2, length($3) - match($3, "_svc") - 13);
          if (name != "") \
              printf("RPC_DEF(%s)\n", name); \
          next; }' > tmp
cat `dirname $0`/../../include/rpc_unsupported.m4 tmp | m4 > rpc_unsupported.c
rm tmp
