#! /bin/sh
#
# Test Coverage Estimation
# Process TCE for all NUT images
#
#
# Copyright (C) 2005 Test Environment authors (see file AUTHORS in
# the root directory of the distribution).
#
# Test Environment is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# Test Environment is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA  02111-1307  USA
#
#
# Author: Elena Vengerova <Elena.Vengerova@oktetlabs.ru>
#
# $Id$
#

PARSER=`dirname $0`/../share/te_builder/nut.m4
cat $PARSER $1 | m4 > ${TE_TMP}/nut.conf.processed
. ${TE_TMP}/nut.conf.processed

for i in $NUTS ; do
    NUT_SOURCES=`eval echo '$NUT_'$i'_SOURCES'`
    if test -z "$NUT_SOURCES" ; then continue; fi
    TA_LIST=`eval echo '$NUT_'$i'_TCE_TA'`
    if test -z "$TA_LIST" ; then continue; fi
    for ta in $TA_LIST ; do
        echo TE $ta
        tce_report ${TCE_REPORT_OPTS} ${TE_TMP}/tce_${ta} \
                   ${TE_LOG_DIR}/${i}_coverage.log \
                   ${NUT_SOURCES} || exit 1
    done                                      
    tce_summary ${TCES_OPTS} ${TE_LOG_DIR}/${i}_coverage.log \
                >${TE_LOG_DIR}/${i}_coverage.html || exit 1
done

