#!/bin/sh

gct.exec -D__GNUC__ "$@"
exit $?

# Use this shell script when ``cc'' is a GNU C compiler.  If it's a
# version 2 C compiler, you may need to use gct-gcc2, but try this
# script first.
# You can use GCT with a GNU C compiler not named ``cc'' by using this
# line:
#
# gct.exec -D__GNUC__ -test-cc NAME_OF_YOUR_COMPILER "$@"
#
# Normally, GCT's installer has selected one of the gct-* 
# scripts to be called ``gct''.
