#!/bin/sh

gct.exec "$@"
exit $?

# Use this shell script when ``cc'' is an ANSI C compiler.  You can
# use GCT with an ANSI compiler not named ``cc'' by using this line:
#
# gct.exec -test-cc NAME_OF_YOUR_COMPILER "$@"
#
# Normally, GCT's installer has selected one of the gct-* 
# scripts to be called ``gct''.
