#!/usr/bin/python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 OKTET Labs Ltd. All rights reserved.
#
# Script for generating JSON to be imported by Bublik.

import argparse
import json
from datetime import datetime
from copy import copy

def format_ts(ts):
    """Construct date and time string for a given timestamp."""
    d = datetime.fromtimestamp(float(ts))
    return d.strftime('%Y.%m.%d %H:%M:%S.') + f'{d.microsecond // 1000:03}'

def del_none_fields(d):
    """Delete fields with None values."""
    if d is None:
        return

    if type(d) == list:
        for el in d:
            del_none_fields(el)

        return

    if type(d) != dict:
        return

    for key in list(d):
        if d[key] is None:
            del d[key]
        else:
            del_none_fields(d[key])

def parse_test_start(obj, msg):
    """Parse 'test_start' MI message."""
    obj['name'] = msg['name']

    obj['type'] = msg.get('node_type')
    obj['hash'] = msg.get('hash') or ""
    obj['test_id'] = msg.get('id')
    obj['plan_id'] = msg.get('plan_id')

    if 'tin' in msg:
        obj['tin'] = msg['tin']
    else:
        obj['tin'] = -1

    obj['reqs'] = msg.get('reqs') or []
    obj['objective'] = msg.get('objective') or ''

    params = {}
    for param in (msg.get('params') or []):
        params[param[0]] = param[1]

    obj['params'] = params

def parse_test_end(obj, msg):
    """Parse 'test_end' MI message."""
    obj['err'] = msg.get('error') or ''

    obtained = {}
    if 'obtained' in msg:
        obtained['result'] = msg['obtained']

    expected = msg.get('expected')
    exp_notes = msg.get('exp_notes')
    exp_key = msg.get('exp_key')
    tags_expr = msg.get('tags_expr')

    if not expected:
        # Tester does not store expected results if the obtained
        # result is expected.
        target = obtained
    else:
        expected = {'results': expected}
        target = expected

    if exp_key:
        target['key'] = exp_key
    if exp_notes:
        target['notes'] = exp_notes
    if tags_expr:
        target['tag_expression'] = tags_expr

    del_none_fields(obtained)
    del_none_fields(expected)
    if obtained:
        obj['obtained'] = obtained
    if expected:
        obj['expected'] = expected

def main():
    """Main function of this script."""
    parser = argparse.ArgumentParser(
                        prog='rgt-bublik-json',
                        description='Generate JSON for Bublik')
    parser.add_argument('-m', '--mi-log', help='Log with MI messages',
                        required=True)
    parser.add_argument('-o', '--output', help='Output file location',
                        default='/dev/stdout')

    args = parser.parse_args()

    top = {'iters': []}
    path = []
    objs = [top]

    with open(args.mi_log, 'r') as f:
        while True:
            ts = f.readline().strip()
            if not ts:
                break

            ts = float(ts)
            formatted_ts = format_ts(ts)
            mi = json.loads(f.readline())

            if 'start_ts' not in top:
                top['start_ts'] = formatted_ts

            top['end_ts'] = formatted_ts

            mi_type = mi['type']

            if mi_type == 'trc_tags':
                tags = {}
                for tag in mi['tags']:
                    name = tag['name']
                    value = tag.get('value')

                    tags[name] = value

                if 'tags' in top:
                    top['tags'].update(tags)
                else:
                    top['tags'] = tags

            elif mi_type == 'test_plan':
                top['plan'] = mi['plan']

            elif mi_type == 'test_start':
                msg = mi['msg']

                obj = {}
                obj['iters'] = []
                obj['start_ts'] = formatted_ts

                parse_test_start(obj, msg)

                if obj['type'] != 'session':
                    path.append(msg['name'])

                obj['path'] = copy(path)
                obj['path_str'] = '/'.join(path)

                objs[-1]['iters'].append(obj)
                objs.append(obj)

            elif mi_type == 'test_end':
                obj = objs.pop()

                obj['end_ts'] = formatted_ts

                msg = mi['msg']
                parse_test_end(obj, msg)

                if obj['type'] != 'session':
                    path.pop()

            elif mi_type == 'measurement':
                obj = objs[-1]

                if 'measurements' not in obj:
                    obj['measurements'] = []

                obj['measurements'].append(mi)

    # If testing was terminated abnormally, 'test_end' messages
    # may be unavailable for final test/session/package. Add
    # INCOMPLETE results for them.
    while len(objs) > 1:
        obj = objs.pop()
        obj['end_ts'] = top['end_ts']
        obj['obtained'] = {
            'result': {
                'status': 'INCOMPLETE'
            }
        }

    with open(args.output, 'w') as f:
        json.dump(top, f)

main()
