#!/usr/bin/perl
#
# Test Environment: Testing Results Comparator
#
# Oktetlabs bugzilla page parser script
#
# Copyright (C) 2004-2022 OKTET Labs.
#
# Author Alexander Kukuta <Alexander.Kukuta@oktetlabs.ru>
#
#

printf("<bugs>\n");

# Iterate through the list of Bug IDs
for my $bug_name (@ARGV)
{
    my $bug_id = ();
    if ($bug_name =~ m/([\w\s-_]*)/i)
    {
        $bug_id = $1;
    }

    printf("<bug bug-id=\"%s\"", $bug_id);
    printf(" priority=\"-\"");
    printf(" status=\"-\"");
    printf(" summary=\"-\"");
    printf(" project=\"-\"");
    printf(" tags=\"-\"");
    printf("/>\n");
}

printf("</bugs>\n");
