#!/bin/sh
# the next line restarts using tclsh \
exec tclsh "$0" "$@"

source "test12.tcl"
source "test_gen.tcl"

set test_cases_pass [list \
    "A"   "CA"          \
    "A"   "AS"          \
    ""    "BB"          \
    ""    ""            \
    "ABS" "B1"          \
    "Tester" "B"        \
    "Tester" "C"        \
    "A"      "B"        \
    "A"      "A"        \
    "C"      "C"        \
    ""       "B"        \
]

set test_cases_fail [list \
    "Tester" "A"      \
    "Tester" "BB"     \
    "Tester" "CC"     \
    "Tester" ""       \
    "Tester" "AA"     \
]


foreach { entity user } $test_cases_fail {
    check_rgt_entity_filter $entity $user "fail"
}

foreach { entity user } $test_cases_pass {
    check_rgt_entity_filter $entity $user "pass"
}
