/** @file
 * @brief Testing Results Comparator
 *
 * Definition of data types and API to use TRC.
 *
 *
 * Copyright (C) 2006 Test Environment authors (see file AUTHORS
 * in the root directory of the distribution).
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1
 * of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA  02111-1307  USA
 *
 *
 * @author Andrew Rybchenko <Andrew.Rybchenko@oktetlabs.ru>
 *
 * $Id$
 */

#ifndef __TE_TRC_H__
#define __TE_TRC_H__

#include "te_errno.h"
#include "te_queue.h"

#ifdef __cplusplus
extern "C" {
#endif


/*
 * Testing Results Comparator database interface
 */

/* Forward declaration of the Testing Results Comparator instance */
struct te_trc;
/* Forward declaration of the TRC database instance */
struct te_trc_db;

/**
 * Open TRC database.
 *
 * @param path          Path to the database
 * @param p_trc_db      Location for TRC database instance handle
 *
 * @return Status code.
 *
 * @sa trc_db_close
 */
extern te_errno trc_db_open(const char *path, struct te_trc_db **p_trc_db);

/**
 * Close TRC database.
 *
 * @param trc_db        TRC database instance handle
 */
extern void trc_db_close(struct te_trc_db *trc_db);


/*
 * Testing Results Comparator instance.
 */

/**
 * Initialize TRC instance.
 *
 * @param p_trci        Location for TRC instance handle
 *
 * @return Status code.
 */
extern te_errno trc_init(struct te_trc **p_trci);

/**
 * Set TRC database.
 *
 * @param trci          TRC instance handle
 * @param db            TRC database instance handle
 *
 * @return Status code.
 */
extern te_errno trc_set_db(struct te_trc    *trci,
                           struct te_trc_db *trc_db);

/**
 * Initialize TRC instance.
 *
 * @param trci          TRC instance handle
 * @param iut_id        IUT identification tags
 *
 * @return Status code.
 */
extern te_errno trc_add_iut_id(struct te_trc *trci, const trc_tags *iut_id);

/**
 * Free TRC instance.
 *
 * @param trci          TRC instance handle
 */
extern void trc_free(struct te_trc *trci);


/**
 * Statuses of test execution.
 */
typedef enum te_test_status {
    TE_TEST_PASSED,     /**< Discovered IUT behaviour is correct from
                             the test point of view */
    TE_TEST_SKIPPED,    /**< The test is skipped because of target
                             requirements specified by user */
    TE_TEST_FAILED,     /**< Discovered IUT behaviour is incorrect
                             from test point of view or some internal
                             error occur */
    TE_TEST_KILLED,     /**< Test application was killed by some signal */
    TE_TEST_CORED,      /**< Test application was killed by SIGSEGV
                             signal and dumped core into a file */
    TE_TEST_FAKED,      /**< Test execution is just faked by the Tester */
} te_test_status;

/**
 * Verdict generated by the test during execution.
 */
typedef struct te_test_verdict {
    TAILQ_ENTRY(te_test_verdict)    links;  /**< Links to create queue
                                                 of verdicts */
    char                           *str;    /**< Verdict string */
} te_test_verdict;

/**
 * Test result representation.
 */
typedef struct te_test_result {
    te_test_status                  status;     /**< Status of the test
                                                     execution */
    TAILQ_HEAD(, te_test_verdict)   verdicts;   /**< Verdicts generated
                                                     by the test during
                                                     execution */
} te_test_result;

/**
 * Single test result with auxiliary information for TRC.
 */
typedef struct trc_test_result_entry {
    TAILQ_ENTRY(trc_test_result_entry)  links;  /**< List links */
    te_test_result                      result; /**< Test result */
    /* Auxiliary information */
} trc_test_result_entry;

/**
 * Expected test result.
 */
typedef struct trc_test_result {

    TAILQ_HEAD(, trc_test_result_entry) results;
    /* Auxiliary information */
} trc_test_result;

#ifdef __cplusplus
} /* extern "C" */
#endif
#endif /* !__TE_TRC_H__ */
