/* acse_soapStub.h
   Generated by gSOAP 2.7.9l from cwmp_acs.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef acse_soapStub_H
#define acse_soapStub_H
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (11)
/* xsd:boolean */
enum xsd__boolean {xsd__boolean__false_ = 0, xsd__boolean__true_ = 1};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterAttributesStruct_Notification
#define SOAP_TYPE__cwmp__SetParameterAttributesStruct_Notification (91)
/* cwmp:SetParameterAttributesStruct-Notification */
enum _cwmp__SetParameterAttributesStruct_Notification {_cwmp__SetParameterAttributesStruct_Notification__0 = 0, _cwmp__SetParameterAttributesStruct_Notification__1 = 1, _cwmp__SetParameterAttributesStruct_Notification__2 = 2};
#endif

#ifndef SOAP_TYPE__cwmp__ParameterAttributeStruct_Notification
#define SOAP_TYPE__cwmp__ParameterAttributeStruct_Notification (93)
/* cwmp:ParameterAttributeStruct-Notification */
enum _cwmp__ParameterAttributeStruct_Notification {_cwmp__ParameterAttributeStruct_Notification__0 = 0, _cwmp__ParameterAttributeStruct_Notification__1 = 1, _cwmp__ParameterAttributeStruct_Notification__2 = 2};
#endif

#ifndef SOAP_TYPE__cwmp__QueuedTransferStruct_State
#define SOAP_TYPE__cwmp__QueuedTransferStruct_State (94)
/* cwmp:QueuedTransferStruct-State */
enum _cwmp__QueuedTransferStruct_State {_cwmp__QueuedTransferStruct_State__1 = 1, _cwmp__QueuedTransferStruct_State__2 = 2, _cwmp__QueuedTransferStruct_State__3 = 3};
#endif

#ifndef SOAP_TYPE__cwmp__AllQueuedTransferStruct_State
#define SOAP_TYPE__cwmp__AllQueuedTransferStruct_State (95)
/* cwmp:AllQueuedTransferStruct-State */
enum _cwmp__AllQueuedTransferStruct_State {_cwmp__AllQueuedTransferStruct_State__1 = 1, _cwmp__AllQueuedTransferStruct_State__2 = 2, _cwmp__AllQueuedTransferStruct_State__3 = 3};
#endif

#ifndef SOAP_TYPE__cwmp__OptionStruct_State
#define SOAP_TYPE__cwmp__OptionStruct_State (96)
/* cwmp:OptionStruct-State */
enum _cwmp__OptionStruct_State {_cwmp__OptionStruct_State__0 = 0, _cwmp__OptionStruct_State__1 = 1, _cwmp__OptionStruct_State__2 = 2, _cwmp__OptionStruct_State__3 = 3};
#endif

#ifndef SOAP_TYPE__cwmp__OptionStruct_Mode
#define SOAP_TYPE__cwmp__OptionStruct_Mode (97)
/* cwmp:OptionStruct-Mode */
enum _cwmp__OptionStruct_Mode {_cwmp__OptionStruct_Mode__0 = 0, _cwmp__OptionStruct_Mode__1 = 1, _cwmp__OptionStruct_Mode__2 = 2};
#endif

#ifndef SOAP_TYPE__cwmp__OptionStruct_IsTransferable
#define SOAP_TYPE__cwmp__OptionStruct_IsTransferable (100)
/* cwmp:OptionStruct-IsTransferable */
enum _cwmp__OptionStruct_IsTransferable {_cwmp__OptionStruct_IsTransferable__0 = 0, _cwmp__OptionStruct_IsTransferable__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterValuesResponse_Status
#define SOAP_TYPE__cwmp__SetParameterValuesResponse_Status (105)
/* cwmp:SetParameterValuesResponse-Status */
enum _cwmp__SetParameterValuesResponse_Status {_cwmp__SetParameterValuesResponse_Status__0 = 0, _cwmp__SetParameterValuesResponse_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__AddObjectResponse_Status
#define SOAP_TYPE__cwmp__AddObjectResponse_Status (110)
/* cwmp:AddObjectResponse-Status */
enum _cwmp__AddObjectResponse_Status {_cwmp__AddObjectResponse_Status__0 = 0, _cwmp__AddObjectResponse_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__DeleteObjectResponse_Status
#define SOAP_TYPE__cwmp__DeleteObjectResponse_Status (111)
/* cwmp:DeleteObjectResponse-Status */
enum _cwmp__DeleteObjectResponse_Status {_cwmp__DeleteObjectResponse_Status__0 = 0, _cwmp__DeleteObjectResponse_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__DownloadResponse_Status
#define SOAP_TYPE__cwmp__DownloadResponse_Status (112)
/* cwmp:DownloadResponse-Status */
enum _cwmp__DownloadResponse_Status {_cwmp__DownloadResponse_Status__0 = 0, _cwmp__DownloadResponse_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__UploadResponse_Status
#define SOAP_TYPE__cwmp__UploadResponse_Status (116)
/* cwmp:UploadResponse-Status */
enum _cwmp__UploadResponse_Status {_cwmp__UploadResponse_Status__0 = 0, _cwmp__UploadResponse_Status__1 = 1};
#endif

/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_SOAP_ENC__base64
#define SOAP_TYPE_SOAP_ENC__base64 (6)
/* Base64 schema type: */
struct SOAP_ENC__base64
{
	unsigned char *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmp__FaultStruct
#define SOAP_TYPE_cwmp__FaultStruct (14)
/* cwmp:FaultStruct */
struct cwmp__FaultStruct
{
	char *FaultCode;	/* required element of type xsd:string */
	char *FaultString;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp__DeviceIdStruct
#define SOAP_TYPE_cwmp__DeviceIdStruct (15)
/* cwmp:DeviceIdStruct */
struct cwmp__DeviceIdStruct
{
	char *Manufacturer;	/* required element of type xsd:string */
	char *OUI;	/* required element of type xsd:string */
	char *ProductClass;	/* required element of type xsd:string */
	char *SerialNumber;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp__EventStruct
#define SOAP_TYPE_cwmp__EventStruct (16)
/* cwmp:EventStruct */
struct cwmp__EventStruct
{
	char *EventCode;	/* required element of type xsd:string */
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE_cwmp__ParameterValueStruct
#define SOAP_TYPE_cwmp__ParameterValueStruct (18)
/* cwmp:ParameterValueStruct */
struct cwmp__ParameterValueStruct
{
	char *Name;	/* required element of type xsd:string */
	int __type;	/* any type of element <Value> (defined below) */
	void *Value;	/* transient */
};
#endif

#ifndef SOAP_TYPE_cwmp__ParameterInfoStruct
#define SOAP_TYPE_cwmp__ParameterInfoStruct (20)
/* cwmp:ParameterInfoStruct */
struct cwmp__ParameterInfoStruct
{
	char *Name;	/* required element of type xsd:string */
	enum xsd__boolean Writable;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_cwmp__SetParameterAttributesStruct
#define SOAP_TYPE_cwmp__SetParameterAttributesStruct (24)
/* cwmp:SetParameterAttributesStruct */
struct cwmp__SetParameterAttributesStruct
{
	char **Name;	/* optional element of type xsd:string */
	enum xsd__boolean NotificationChange;	/* required element of type xsd:boolean */
	enum _cwmp__SetParameterAttributesStruct_Notification Notification;	/* required element of type cwmp:SetParameterAttributesStruct-Notification */
	enum xsd__boolean AccessListChange;	/* required element of type xsd:boolean */
	struct AccessList *AccessList_;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_cwmp__ParameterAttributeStruct
#define SOAP_TYPE_cwmp__ParameterAttributeStruct (26)
/* cwmp:ParameterAttributeStruct */
struct cwmp__ParameterAttributeStruct
{
	char *Name;	/* required element of type xsd:string */
	enum _cwmp__ParameterAttributeStruct_Notification Notification;	/* required element of type cwmp:ParameterAttributeStruct-Notification */
	struct AccessList *AccessList_;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_cwmp__QueuedTransferStruct
#define SOAP_TYPE_cwmp__QueuedTransferStruct (28)
/* cwmp:QueuedTransferStruct */
struct cwmp__QueuedTransferStruct
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
	enum _cwmp__QueuedTransferStruct_State State;	/* required element of type cwmp:QueuedTransferStruct-State */
};
#endif

#ifndef SOAP_TYPE_cwmp__AllQueuedTransferStruct
#define SOAP_TYPE_cwmp__AllQueuedTransferStruct (30)
/* cwmp:AllQueuedTransferStruct */
struct cwmp__AllQueuedTransferStruct
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
	enum _cwmp__AllQueuedTransferStruct_State State;	/* required element of type cwmp:AllQueuedTransferStruct-State */
	enum xsd__boolean IsDownload;	/* required element of type xsd:boolean */
	char *FileType;	/* required element of type xsd:string */
	unsigned int FileSize;	/* required element of type xsd:unsignedInt */
	char *TargetFileName;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp__OptionStruct
#define SOAP_TYPE_cwmp__OptionStruct (33)
/* cwmp:OptionStruct */
struct cwmp__OptionStruct
{
	char *OptionName;	/* required element of type xsd:string */
	unsigned int VoucherSN;	/* required element of type xsd:unsignedInt */
	enum _cwmp__OptionStruct_State State;	/* required element of type cwmp:OptionStruct-State */
	enum _cwmp__OptionStruct_Mode Mode;	/* required element of type cwmp:OptionStruct-Mode */
	time_t StartDate;	/* required element of type xsd:dateTime */
	time_t *ExpirationDate;	/* optional element of type xsd:dateTime */
	enum _cwmp__OptionStruct_IsTransferable IsTransferable;	/* required element of type cwmp:OptionStruct-IsTransferable */
};
#endif

#ifndef SOAP_TYPE_cwmp__ArgStruct
#define SOAP_TYPE_cwmp__ArgStruct (35)
/* cwmp:ArgStruct */
struct cwmp__ArgStruct
{
	char *Name;	/* required element of type xsd:string */
	char *Value;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__Fault_SetParameterValuesFault
#define SOAP_TYPE__cwmp__Fault_SetParameterValuesFault (101)
/* cwmp:Fault-SetParameterValuesFault */
struct _cwmp__Fault_SetParameterValuesFault
{
	char *ParameterName;	/* required element of type xsd:string */
	char *FaultCode;	/* required element of type cwmp:FaultCodeType */
	char *FaultString;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__Fault
#define SOAP_TYPE__cwmp__Fault (39)
/* cwmp:Fault */
struct _cwmp__Fault
{
	char *FaultCode;	/* required element of type cwmp:FaultCodeType */
	char *FaultString;	/* optional element of type xsd:string */
	int __sizeSetParameterValuesFault;	/* sequence of elements <SetParameterValuesFault> */
	struct _cwmp__Fault_SetParameterValuesFault *SetParameterValuesFault;	/* optional element of type cwmp:Fault-SetParameterValuesFault */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetRPCMethods
#define SOAP_TYPE__cwmp__GetRPCMethods (40)
/* cwmp:GetRPCMethods */
struct _cwmp__GetRPCMethods
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetRPCMethodsResponse
#define SOAP_TYPE__cwmp__GetRPCMethodsResponse (41)
/* cwmp:GetRPCMethodsResponse */
struct _cwmp__GetRPCMethodsResponse
{
	struct MethodList *MethodList_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterValues
#define SOAP_TYPE__cwmp__SetParameterValues (42)
/* cwmp:SetParameterValues */
struct _cwmp__SetParameterValues
{
	struct ParameterValueList *ParameterList;	/* required element of type ArrayOfParameterValueStruct */
	char *ParameterKey;	/* required element of type cwmp:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterValuesResponse
#define SOAP_TYPE__cwmp__SetParameterValuesResponse (43)
/* cwmp:SetParameterValuesResponse */
struct _cwmp__SetParameterValuesResponse
{
	enum _cwmp__SetParameterValuesResponse_Status Status;	/* required element of type cwmp:SetParameterValuesResponse-Status */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterValues
#define SOAP_TYPE__cwmp__GetParameterValues (44)
/* cwmp:GetParameterValues */
struct _cwmp__GetParameterValues
{
	struct ParameterNames *ParameterNames_;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterValuesResponse
#define SOAP_TYPE__cwmp__GetParameterValuesResponse (45)
/* cwmp:GetParameterValuesResponse */
struct _cwmp__GetParameterValuesResponse
{
	struct ParameterValueList *ParameterList;	/* required element of type ArrayOfParameterValueStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterNames
#define SOAP_TYPE__cwmp__GetParameterNames (46)
/* cwmp:GetParameterNames */
struct _cwmp__GetParameterNames
{
	char **ParameterPath;	/* optional element of type xsd:string */
	enum xsd__boolean NextLevel;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterNamesResponse
#define SOAP_TYPE__cwmp__GetParameterNamesResponse (47)
/* cwmp:GetParameterNamesResponse */
struct _cwmp__GetParameterNamesResponse
{
	struct ParameterInfoList *ParameterList;	/* required element of type ArrayOfParameterInfoStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterAttributes
#define SOAP_TYPE__cwmp__SetParameterAttributes (48)
/* cwmp:SetParameterAttributes */
struct _cwmp__SetParameterAttributes
{
	struct SetParameterAttributesList *ParameterList;	/* required element of type ArrayOfSetParameterAttributesStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterAttributesResponse
#define SOAP_TYPE__cwmp__SetParameterAttributesResponse (49)
/* cwmp:SetParameterAttributesResponse */
struct _cwmp__SetParameterAttributesResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterAttributes
#define SOAP_TYPE__cwmp__GetParameterAttributes (50)
/* cwmp:GetParameterAttributes */
struct _cwmp__GetParameterAttributes
{
	struct ParameterNames *ParameterNames_;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterAttributesResponse
#define SOAP_TYPE__cwmp__GetParameterAttributesResponse (51)
/* cwmp:GetParameterAttributesResponse */
struct _cwmp__GetParameterAttributesResponse
{
	struct ParameterAttributeList *ParameterList;	/* required element of type ArrayOfParameterAttributeStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__AddObject
#define SOAP_TYPE__cwmp__AddObject (52)
/* cwmp:AddObject */
struct _cwmp__AddObject
{
	char *ObjectName;	/* required element of type cwmp:ObjectNameType */
	char *ParameterKey;	/* required element of type cwmp:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__AddObjectResponse
#define SOAP_TYPE__cwmp__AddObjectResponse (53)
/* cwmp:AddObjectResponse */
struct _cwmp__AddObjectResponse
{
	unsigned int InstanceNumber;	/* required element of type xsd:unsignedInt */
	enum _cwmp__AddObjectResponse_Status Status;	/* required element of type cwmp:AddObjectResponse-Status */
};
#endif

#ifndef SOAP_TYPE__cwmp__DeleteObject
#define SOAP_TYPE__cwmp__DeleteObject (54)
/* cwmp:DeleteObject */
struct _cwmp__DeleteObject
{
	char *ObjectName;	/* required element of type cwmp:ObjectNameType */
	char *ParameterKey;	/* required element of type cwmp:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__DeleteObjectResponse
#define SOAP_TYPE__cwmp__DeleteObjectResponse (55)
/* cwmp:DeleteObjectResponse */
struct _cwmp__DeleteObjectResponse
{
	enum _cwmp__DeleteObjectResponse_Status Status;	/* required element of type cwmp:DeleteObjectResponse-Status */
};
#endif

#ifndef SOAP_TYPE__cwmp__Download
#define SOAP_TYPE__cwmp__Download (56)
/* cwmp:Download */
struct _cwmp__Download
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
	char *FileType;	/* required element of type xsd:string */
	char *URL;	/* required element of type xsd:string */
	char *Username;	/* required element of type xsd:string */
	char *Password;	/* required element of type xsd:string */
	unsigned int FileSize;	/* required element of type xsd:unsignedInt */
	char *TargetFileName;	/* required element of type xsd:string */
	unsigned int DelaySeconds;	/* required element of type xsd:unsignedInt */
	char *SuccessURL;	/* required element of type xsd:string */
	char *FailureURL;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__DownloadResponse
#define SOAP_TYPE__cwmp__DownloadResponse (57)
/* cwmp:DownloadResponse */
struct _cwmp__DownloadResponse
{
	enum _cwmp__DownloadResponse_Status Status;	/* required element of type cwmp:DownloadResponse-Status */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__cwmp__Reboot
#define SOAP_TYPE__cwmp__Reboot (58)
/* cwmp:Reboot */
struct _cwmp__Reboot
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__RebootResponse
#define SOAP_TYPE__cwmp__RebootResponse (59)
/* cwmp:RebootResponse */
struct _cwmp__RebootResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetQueuedTransfers
#define SOAP_TYPE__cwmp__GetQueuedTransfers (60)
/* cwmp:GetQueuedTransfers */
struct _cwmp__GetQueuedTransfers
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetQueuedTransfersResponse
#define SOAP_TYPE__cwmp__GetQueuedTransfersResponse (61)
/* cwmp:GetQueuedTransfersResponse */
struct _cwmp__GetQueuedTransfersResponse
{
	struct TransferList *TransferList_;	/* required element of type ArrayOfQueuedTransferStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__ScheduleInform
#define SOAP_TYPE__cwmp__ScheduleInform (62)
/* cwmp:ScheduleInform */
struct _cwmp__ScheduleInform
{
	unsigned int DelaySeconds;	/* required element of type xsd:unsignedInt */
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__ScheduleInformResponse
#define SOAP_TYPE__cwmp__ScheduleInformResponse (63)
/* cwmp:ScheduleInformResponse */
struct _cwmp__ScheduleInformResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__SetVouchers
#define SOAP_TYPE__cwmp__SetVouchers (64)
/* cwmp:SetVouchers */
struct _cwmp__SetVouchers
{
	struct VoucherList *VoucherList_;	/* required element of type ArrayOfbase64 */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetVouchersResponse
#define SOAP_TYPE__cwmp__SetVouchersResponse (65)
/* cwmp:SetVouchersResponse */
struct _cwmp__SetVouchersResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetOptions
#define SOAP_TYPE__cwmp__GetOptions (66)
/* cwmp:GetOptions */
struct _cwmp__GetOptions
{
	char *OptionName;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetOptionsResponse
#define SOAP_TYPE__cwmp__GetOptionsResponse (67)
/* cwmp:GetOptionsResponse */
struct _cwmp__GetOptionsResponse
{
	struct OptionList *OptionList_;	/* required element of type ArrayOfOptionStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__Upload
#define SOAP_TYPE__cwmp__Upload (68)
/* cwmp:Upload */
struct _cwmp__Upload
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
	char *FileType;	/* required element of type xsd:string */
	char *URL;	/* required element of type xsd:string */
	char *Username;	/* required element of type xsd:string */
	char *Password;	/* required element of type xsd:string */
	unsigned int DelaySeconds;	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE__cwmp__UploadResponse
#define SOAP_TYPE__cwmp__UploadResponse (69)
/* cwmp:UploadResponse */
struct _cwmp__UploadResponse
{
	enum _cwmp__UploadResponse_Status Status;	/* required element of type cwmp:UploadResponse-Status */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__cwmp__FactoryReset
#define SOAP_TYPE__cwmp__FactoryReset (70)
/* cwmp:FactoryReset */
struct _cwmp__FactoryReset
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__FactoryResetResponse
#define SOAP_TYPE__cwmp__FactoryResetResponse (71)
/* cwmp:FactoryResetResponse */
struct _cwmp__FactoryResetResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetAllQueuedTransfers
#define SOAP_TYPE__cwmp__GetAllQueuedTransfers (72)
/* cwmp:GetAllQueuedTransfers */
struct _cwmp__GetAllQueuedTransfers
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetAllQueuedTransfersResponse
#define SOAP_TYPE__cwmp__GetAllQueuedTransfersResponse (73)
/* cwmp:GetAllQueuedTransfersResponse */
struct _cwmp__GetAllQueuedTransfersResponse
{
	struct AllTransferList *TransferList_;	/* required element of type ArrayOfAllQueuedTransferStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__Inform
#define SOAP_TYPE__cwmp__Inform (74)
/* cwmp:Inform */
struct _cwmp__Inform
{
	struct cwmp__DeviceIdStruct *DeviceId;	/* required element of type cwmp:DeviceIdStruct */
	struct EventList *Event;	/* required element of type ArrayOfEventStruct */
	unsigned int MaxEnvelopes;	/* required element of type xsd:unsignedInt */
	time_t CurrentTime;	/* required element of type xsd:dateTime */
	unsigned int RetryCount;	/* required element of type xsd:unsignedInt */
	struct ParameterValueList *ParameterList;	/* required element of type ArrayOfParameterValueStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__InformResponse
#define SOAP_TYPE__cwmp__InformResponse (75)
/* cwmp:InformResponse */
struct _cwmp__InformResponse
{
	unsigned int MaxEnvelopes;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE__cwmp__TransferComplete
#define SOAP_TYPE__cwmp__TransferComplete (76)
/* cwmp:TransferComplete */
struct _cwmp__TransferComplete
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
	struct cwmp__FaultStruct *FaultStruct;	/* required element of type cwmp:FaultStruct */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__cwmp__TransferCompleteResponse
#define SOAP_TYPE__cwmp__TransferCompleteResponse (77)
/* cwmp:TransferCompleteResponse */
struct _cwmp__TransferCompleteResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__AutonomousTransferComplete
#define SOAP_TYPE__cwmp__AutonomousTransferComplete (78)
/* cwmp:AutonomousTransferComplete */
struct _cwmp__AutonomousTransferComplete
{
	char *AnnounceURL;	/* required element of type xsd:string */
	char *TransferURL;	/* required element of type xsd:string */
	enum xsd__boolean IsDownload;	/* required element of type xsd:boolean */
	char *FileType;	/* required element of type xsd:string */
	unsigned int FileSize;	/* required element of type xsd:unsignedInt */
	char *TargetFileName;	/* required element of type xsd:string */
	struct cwmp__FaultStruct *FaultStruct;	/* required element of type cwmp:FaultStruct */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__cwmp__AutonomousTransferCompleteResponse
#define SOAP_TYPE__cwmp__AutonomousTransferCompleteResponse (79)
/* cwmp:AutonomousTransferCompleteResponse */
struct _cwmp__AutonomousTransferCompleteResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__Kicked
#define SOAP_TYPE__cwmp__Kicked (80)
/* cwmp:Kicked */
struct _cwmp__Kicked
{
	char *Command;	/* required element of type xsd:string */
	char *Referer;	/* required element of type xsd:string */
	char *Arg;	/* required element of type xsd:string */
	char *Next;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__KickedResponse
#define SOAP_TYPE__cwmp__KickedResponse (81)
/* cwmp:KickedResponse */
struct _cwmp__KickedResponse
{
	char *NextURL;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__RequestDownload
#define SOAP_TYPE__cwmp__RequestDownload (82)
/* cwmp:RequestDownload */
struct _cwmp__RequestDownload
{
	char *FileType;	/* required element of type xsd:string */
	struct FileTypeArg *FileTypeArg_;	/* required element of type ArrayOfArgStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__RequestDownloadResponse
#define SOAP_TYPE__cwmp__RequestDownloadResponse (83)
/* cwmp:RequestDownloadResponse */
struct _cwmp__RequestDownloadResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_MethodList
#define SOAP_TYPE_MethodList (13)
/* SOAP encoded array of xsd:string schema type: */
struct MethodList
{
	char **__ptrstring;
	int __size;
};
#endif

#ifndef SOAP_TYPE_EventList
#define SOAP_TYPE_EventList (17)
/* SOAP encoded array of cwmp:EventStruct schema type: */
struct EventList
{
	struct cwmp__EventStruct **__ptrEventStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ParameterValueList
#define SOAP_TYPE_ParameterValueList (19)
/* SOAP encoded array of cwmp:ParameterValueStruct schema type: */
struct ParameterValueList
{
	struct cwmp__ParameterValueStruct **__ptrParameterValueStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ParameterInfoList
#define SOAP_TYPE_ParameterInfoList (21)
/* SOAP encoded array of cwmp:ParameterInfoStruct schema type: */
struct ParameterInfoList
{
	struct cwmp__ParameterInfoStruct **__ptrParameterInfoStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ParameterNames
#define SOAP_TYPE_ParameterNames (22)
/* SOAP encoded array of xsd:string schema type: */
struct ParameterNames
{
	char **__ptrstring;
	int __size;
};
#endif

#ifndef SOAP_TYPE_AccessList
#define SOAP_TYPE_AccessList (23)
/* SOAP encoded array of xsd:string schema type: */
struct AccessList
{
	char **__ptrstring;
	int __size;
};
#endif

#ifndef SOAP_TYPE_SetParameterAttributesList
#define SOAP_TYPE_SetParameterAttributesList (25)
/* SOAP encoded array of cwmp:SetParameterAttributesStruct schema type: */
struct SetParameterAttributesList
{
	struct cwmp__SetParameterAttributesStruct **__ptrSetParameterAttributesStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ParameterAttributeList
#define SOAP_TYPE_ParameterAttributeList (27)
/* SOAP encoded array of cwmp:ParameterAttributeStruct schema type: */
struct ParameterAttributeList
{
	struct cwmp__ParameterAttributeStruct **__ptrParameterAttributeStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_TransferList
#define SOAP_TYPE_TransferList (29)
/* SOAP encoded array of cwmp:QueuedTransferStruct schema type: */
struct TransferList
{
	struct cwmp__QueuedTransferStruct **__ptrQueuedTransferStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_AllTransferList
#define SOAP_TYPE_AllTransferList (31)
/* SOAP encoded array of cwmp:AllQueuedTransferStruct schema type: */
struct AllTransferList
{
	struct cwmp__AllQueuedTransferStruct **__ptrAllQueuedTransferStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_VoucherList
#define SOAP_TYPE_VoucherList (32)
/* SOAP encoded array of SOAP-ENC:base64 schema type: */
struct VoucherList
{
	struct SOAP_ENC__base64 **__ptrbase64;
	int __size;
};
#endif

#ifndef SOAP_TYPE_OptionList
#define SOAP_TYPE_OptionList (34)
/* SOAP encoded array of cwmp:OptionStruct schema type: */
struct OptionList
{
	struct cwmp__OptionStruct **__ptrOptionStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_FileTypeArg
#define SOAP_TYPE_FileTypeArg (36)
/* SOAP encoded array of cwmp:ArgStruct schema type: */
struct FileTypeArg
{
	struct cwmp__ArgStruct **__ptrArgStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE__cwmp__ID
#define SOAP_TYPE__cwmp__ID (37)
/* Primitive cwmp:ID schema type: */
struct _cwmp__ID
{
	char *__item;
	char *SOAP_ENV__mustUnderstand;	/* required attribute of type SOAP-ENV:mustUnderstand */
};
#endif

#ifndef SOAP_TYPE__cwmp__HoldRequests
#define SOAP_TYPE__cwmp__HoldRequests (38)
/* Primitive cwmp:HoldRequests schema type: */
struct _cwmp__HoldRequests
{
	unsigned int __item;
	char *SOAP_ENV__mustUnderstand;	/* required attribute of type SOAP-ENV:mustUnderstand */
};
#endif

#ifndef SOAP_TYPE___cwmp__GetRPCMethods
#define SOAP_TYPE___cwmp__GetRPCMethods (145)
/* Operation wrapper: */
struct __cwmp__GetRPCMethods
{
	struct _cwmp__GetRPCMethods *cwmp__GetRPCMethods;	/* optional element of type cwmp:GetRPCMethods */
};
#endif

#ifndef SOAP_TYPE___cwmp__Inform
#define SOAP_TYPE___cwmp__Inform (149)
/* Operation wrapper: */
struct __cwmp__Inform
{
	struct _cwmp__Inform *cwmp__Inform;	/* optional element of type cwmp:Inform */
};
#endif

#ifndef SOAP_TYPE___cwmp__TransferComplete
#define SOAP_TYPE___cwmp__TransferComplete (153)
/* Operation wrapper: */
struct __cwmp__TransferComplete
{
	struct _cwmp__TransferComplete *cwmp__TransferComplete;	/* optional element of type cwmp:TransferComplete */
};
#endif

#ifndef SOAP_TYPE___cwmp__AutonomousTransferComplete
#define SOAP_TYPE___cwmp__AutonomousTransferComplete (157)
/* Operation wrapper: */
struct __cwmp__AutonomousTransferComplete
{
	struct _cwmp__AutonomousTransferComplete *cwmp__AutonomousTransferComplete;	/* optional element of type cwmp:AutonomousTransferComplete */
};
#endif

#ifndef SOAP_TYPE___cwmp__RequestDownload
#define SOAP_TYPE___cwmp__RequestDownload (161)
/* Operation wrapper: */
struct __cwmp__RequestDownload
{
	struct _cwmp__RequestDownload *cwmp__RequestDownload;	/* optional element of type cwmp:RequestDownload */
};
#endif

#ifndef SOAP_TYPE___cwmp__Kicked
#define SOAP_TYPE___cwmp__Kicked (165)
/* Operation wrapper: */
struct __cwmp__Kicked
{
	struct _cwmp__Kicked *cwmp__Kicked;	/* optional element of type cwmp:Kicked */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (166)
/* SOAP Header: */
struct SOAP_ENV__Header
{
	struct _cwmp__HoldRequests *cwmp__HoldRequests;	/* optional element of type cwmp:HoldRequests */
	struct _cwmp__ID *cwmp__ID;	/* optional element of type cwmp:ID */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (169)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (171)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (172)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (173)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (4)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE_xsd__anySimpleType
#define SOAP_TYPE_xsd__anySimpleType (10)
typedef char *xsd__anySimpleType;
#endif

#ifndef SOAP_TYPE__SOAP_ENV__mustUnderstand
#define SOAP_TYPE__SOAP_ENV__mustUnderstand (12)
typedef char *_SOAP_ENV__mustUnderstand;
#endif

#ifndef SOAP_TYPE_cwmp__FaultCodeType
#define SOAP_TYPE_cwmp__FaultCodeType (84)
typedef char *cwmp__FaultCodeType;
#endif

#ifndef SOAP_TYPE_cwmp__ParameterKeyType
#define SOAP_TYPE_cwmp__ParameterKeyType (85)
typedef char *cwmp__ParameterKeyType;
#endif

#ifndef SOAP_TYPE_cwmp__CommandKeyType
#define SOAP_TYPE_cwmp__CommandKeyType (86)
typedef char *cwmp__CommandKeyType;
#endif

#ifndef SOAP_TYPE_cwmp__ObjectNameType
#define SOAP_TYPE_cwmp__ObjectNameType (87)
typedef char *cwmp__ObjectNameType;
#endif


/******************************************************************************\
 *                                                                            *
 * Typedef Synonyms                                                           *
 *                                                                            *
\******************************************************************************/

typedef struct cwmp__FaultStruct cwmp__FaultStruct;
typedef struct cwmp__DeviceIdStruct cwmp__DeviceIdStruct;
typedef struct cwmp__EventStruct cwmp__EventStruct;
typedef struct cwmp__ParameterValueStruct cwmp__ParameterValueStruct;
typedef struct cwmp__ParameterInfoStruct cwmp__ParameterInfoStruct;
typedef struct cwmp__SetParameterAttributesStruct cwmp__SetParameterAttributesStruct;
typedef struct cwmp__ParameterAttributeStruct cwmp__ParameterAttributeStruct;
typedef struct cwmp__QueuedTransferStruct cwmp__QueuedTransferStruct;
typedef struct cwmp__AllQueuedTransferStruct cwmp__AllQueuedTransferStruct;
typedef struct cwmp__OptionStruct cwmp__OptionStruct;
typedef struct cwmp__ArgStruct cwmp__ArgStruct;
typedef struct _cwmp__Fault _cwmp__Fault;
typedef struct _cwmp__GetRPCMethods _cwmp__GetRPCMethods;
typedef struct _cwmp__GetRPCMethodsResponse _cwmp__GetRPCMethodsResponse;
typedef struct _cwmp__SetParameterValues _cwmp__SetParameterValues;
typedef struct _cwmp__SetParameterValuesResponse _cwmp__SetParameterValuesResponse;
typedef struct _cwmp__GetParameterValues _cwmp__GetParameterValues;
typedef struct _cwmp__GetParameterValuesResponse _cwmp__GetParameterValuesResponse;
typedef struct _cwmp__GetParameterNames _cwmp__GetParameterNames;
typedef struct _cwmp__GetParameterNamesResponse _cwmp__GetParameterNamesResponse;
typedef struct _cwmp__SetParameterAttributes _cwmp__SetParameterAttributes;
typedef struct _cwmp__SetParameterAttributesResponse _cwmp__SetParameterAttributesResponse;
typedef struct _cwmp__GetParameterAttributes _cwmp__GetParameterAttributes;
typedef struct _cwmp__GetParameterAttributesResponse _cwmp__GetParameterAttributesResponse;
typedef struct _cwmp__AddObject _cwmp__AddObject;
typedef struct _cwmp__AddObjectResponse _cwmp__AddObjectResponse;
typedef struct _cwmp__DeleteObject _cwmp__DeleteObject;
typedef struct _cwmp__DeleteObjectResponse _cwmp__DeleteObjectResponse;
typedef struct _cwmp__Download _cwmp__Download;
typedef struct _cwmp__DownloadResponse _cwmp__DownloadResponse;
typedef struct _cwmp__Reboot _cwmp__Reboot;
typedef struct _cwmp__RebootResponse _cwmp__RebootResponse;
typedef struct _cwmp__GetQueuedTransfers _cwmp__GetQueuedTransfers;
typedef struct _cwmp__GetQueuedTransfersResponse _cwmp__GetQueuedTransfersResponse;
typedef struct _cwmp__ScheduleInform _cwmp__ScheduleInform;
typedef struct _cwmp__ScheduleInformResponse _cwmp__ScheduleInformResponse;
typedef struct _cwmp__SetVouchers _cwmp__SetVouchers;
typedef struct _cwmp__SetVouchersResponse _cwmp__SetVouchersResponse;
typedef struct _cwmp__GetOptions _cwmp__GetOptions;
typedef struct _cwmp__GetOptionsResponse _cwmp__GetOptionsResponse;
typedef struct _cwmp__Upload _cwmp__Upload;
typedef struct _cwmp__UploadResponse _cwmp__UploadResponse;
typedef struct _cwmp__FactoryReset _cwmp__FactoryReset;
typedef struct _cwmp__FactoryResetResponse _cwmp__FactoryResetResponse;
typedef struct _cwmp__GetAllQueuedTransfers _cwmp__GetAllQueuedTransfers;
typedef struct _cwmp__GetAllQueuedTransfersResponse _cwmp__GetAllQueuedTransfersResponse;
typedef struct _cwmp__Inform _cwmp__Inform;
typedef struct _cwmp__InformResponse _cwmp__InformResponse;
typedef struct _cwmp__TransferComplete _cwmp__TransferComplete;
typedef struct _cwmp__TransferCompleteResponse _cwmp__TransferCompleteResponse;
typedef struct _cwmp__AutonomousTransferComplete _cwmp__AutonomousTransferComplete;
typedef struct _cwmp__AutonomousTransferCompleteResponse _cwmp__AutonomousTransferCompleteResponse;
typedef struct _cwmp__Kicked _cwmp__Kicked;
typedef struct _cwmp__KickedResponse _cwmp__KickedResponse;
typedef struct _cwmp__RequestDownload _cwmp__RequestDownload;
typedef struct _cwmp__RequestDownloadResponse _cwmp__RequestDownloadResponse;
typedef struct MethodList MethodList;
typedef struct EventList EventList;
typedef struct ParameterValueList ParameterValueList;
typedef struct ParameterInfoList ParameterInfoList;
typedef struct ParameterNames ParameterNames;
typedef struct AccessList AccessList;
typedef struct SetParameterAttributesList SetParameterAttributesList;
typedef struct ParameterAttributeList ParameterAttributeList;
typedef struct TransferList TransferList;
typedef struct AllTransferList AllTransferList;
typedef struct VoucherList VoucherList;
typedef struct OptionList OptionList;
typedef struct FileTypeArg FileTypeArg;
typedef struct _cwmp__ID _cwmp__ID;
typedef struct _cwmp__HoldRequests _cwmp__HoldRequests;
typedef struct SOAP_ENC__base64 SOAP_ENC__base64;

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operations                                                         *
 *                                                                            *
\******************************************************************************/

extern int acse_cwmp_empty_post(struct soap*); 

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__GetRPCMethods(struct soap*, struct _cwmp__GetRPCMethods *cwmp__GetRPCMethods, struct _cwmp__GetRPCMethodsResponse *cwmp__GetRPCMethodsResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__Inform(struct soap*, struct _cwmp__Inform *cwmp__Inform, struct _cwmp__InformResponse *cwmp__InformResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__TransferComplete(struct soap*, struct _cwmp__TransferComplete *cwmp__TransferComplete, struct _cwmp__TransferCompleteResponse *cwmp__TransferCompleteResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__AutonomousTransferComplete(struct soap*, struct _cwmp__AutonomousTransferComplete *cwmp__AutonomousTransferComplete, struct _cwmp__AutonomousTransferCompleteResponse *cwmp__AutonomousTransferCompleteResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__RequestDownload(struct soap*, struct _cwmp__RequestDownload *cwmp__RequestDownload, struct _cwmp__RequestDownloadResponse *cwmp__RequestDownloadResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__Kicked(struct soap*, struct _cwmp__Kicked *cwmp__Kicked, struct _cwmp__KickedResponse *cwmp__KickedResponse);

/******************************************************************************\
 *                                                                            *
 * Skeletons                                                                  *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetRPCMethods(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__Inform(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__TransferComplete(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__AutonomousTransferComplete(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__RequestDownload(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__Kicked(struct soap*);


#ifdef __cplusplus
}
#endif

#endif

/* End of acse_soapStub.h */
