
TE-NDN-Forwarder
DEFINITIONS ::=
BEGIN

IMPORTS DATA-UNIT FROM TE-NDN-General;



Forwarder-Action-Delay-Params ::= SEQUENCE {
    type      [0] INTEGER {disabled(0), constant(1), random(2)},
    delay_min [1] DATA-UNIT {INTEGER},
    delay_max [2] DATA-UNIT {INTEGER}
}

Forwarder-Action-Bandwidth-Params ::= SEQUENCE {
    type      [0] INTEGER{unlimited(0), limited(1)},
    bps       [1] DATA-UNIT{INTEGER },
    buf_size  [2] DATA-UNIT{INTEGER }
}

Forwarder-Action-Reorder-Params ::= SEQUENCE {
    type            [0] INTEGER {disabled(0), random(1), reversed(2)},
    timeout         [1] DATA-UNIT {INTEGER},
    reorder_size    [2] DATA-UNIT {INTEGER}
}

Forwarder-Action-Drop-Params ::= SEQUENCE {
    type      [0] INTEGER {disabled(0), random(1), pattern(2)},
    rate      [1] DATA-UNIT {INTEGER},
}

Forwarder-Action ::= SEQUENCE {
    id        [0] DATA-UNIT {UniversalString},
    delay     [1] Forwarder-Action-Delay-Params OPTIONAL,
    bandwidth [2] Forwarder-Action-Bandwidth-Params OPTIONAL,
    reorder   [3] Forwarder-Action-Reorder-Params OPTIONAL,
    drop      [4] Forwarder-Action-Drop-Params OPTIONAL
}

END
