#! /bin/sh
#
# Test Coverage Estimation
#
#
# Copyright (C) 2005 Test Environment authors (see file AUTHORS in
# the root directory of the distribution).
#
# Test Environment is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# Test Environment is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA  02111-1307  USA
#
#
# Author Artem V. Andreev <Artem.Andreev@oktetlabs.ru>
#
# $Id$
#

cd `dirname "$1"`
objname=`basename "$1" .da`.o
objname=${objname#.tmp_}
for file in `objdump -l -d "$objname" | sed -e '/^.*\.c:[0-9][0-9]*$/s/:[0-9][0-9]*$//
t
d' | sort | uniq`; do
  cd `dirname $file`
  gcov -c -b -o "$1" `basename $file` >/dev/null
done
