#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 OKTET Labs Ltd. All rights reserved.

set -u

OL_INSTALL_HOOKS="$(command -v ol_install_hooks 2>/dev/null)"
if [[ -z "${OL_INSTALL_HOOKS}" ]]; then
    if [[ -z "${OL_QA_TOOLS:-}" ]]; then
        OL_QA_TOOLS="$(git rev-parse --show-toplevel)/../qa-tools"
    fi
    OL_INSTALL_HOOKS="${OL_QA_TOOLS}/scripts/ol_install_hooks"
    if [[ ! -x "${OL_INSTALL_HOOKS}" ]]; then
        echo "ol_install_hooks cannot be found" >&2
        exit 1
    fi
fi

OL_PREPUSH_HOOK="$(dirname "${OL_INSTALL_HOOKS}")/../hooks/git-prepush-hook"
if [[ ! -x "${OL_PREPUSH_HOOK}" ]]; then
    echo "git-prepush-hook is not found in qa-tools" >&2
    exit
fi

echo "Warning: consider reinstalling the hook from qa-tools:" >&2
echo "         ${OL_INSTALL_HOOKS} --force" >&2

exec "${OL_PREPUSH_HOOK}" "$@"
